tinyMCE.addI18n('en.advanced',{
style_select:"Stili",
font_size:"Dimensione carattere",
fontdefault:"Tipo di carattere",
block:"Formato",
paragraph:"Paragrafo",
div:"Div",
address:"Indirizzo",
pre:"Preformattato",
h1:"Titolo 1",
h2:"Titolo 2",
h3:"Titolo 3",
h4:"Titolo 4",
h5:"Titolo 5",
h6:"Titolo 6",
blockquote:"Blocco di testo",
code:"Codice",
samp:"Codice d'esempio",
dt:"Termine ",
dd:"Descrizione",
bold_desc:"Grassetto (Ctrl+B)",
italic_desc:"Corsivo (Ctrl+I)",
underline_desc:"Sottolineato (Ctrl+U)",
striketrough_desc:"Barrato",
justifyleft_desc:"Allinea a sinistra",
justifycenter_desc:"Allinea al centro",
justifyright_desc:"Allinea a destra",
justifyfull_desc:"Giustificato",
bullist_desc:"Unordered list",
numlist_desc:"Elenco ordinato",
outdent_desc:"Aumenta rientro",
indent_desc:"Diminuisci rientro",
undo_desc:"Annulla (Ctrl+Z)",
redo_desc:"Ripristina (Ctrl+Y)",
link_desc:"Inserisci/Modifica collegamento",
unlink_desc:"Rimuovi collegamento",
image_desc:"Inserisci/modifica immagine",
cleanup_desc:"Pulisci il codice",
code_desc:"Modifica codice HTML",
sub_desc:"Pedice",
sup_desc:"Apice",
hr_desc:"Inserisci righello orizzontale",
removeformat_desc:"Rimuovi la formattazione",
custom1_desc:"Inserisci qui la descrizione",
forecolor_desc:"Seleziona il colore del testo",
backcolor_desc:"Seleziona il colore dello sfondo",
charmap_desc:"Inserisci il carattere",
visualaid_desc:"Imposta guidelines/elementi invisibili",
anchor_desc:"Inserisci/modifica ancoraggio",
cut_desc:"Taglia",
copy_desc:"Copia",
paste_desc:"Incolla",
image_props_desc:"Proprietà immagine",
newdocument_desc:"Nuovo documento",
help_desc:"Aiuto",
blockquote_desc:"Blocco di testo",
clipboard_msg:"Copia/Taglia/Incolla non è disponibile in Mozilla e Firefox.\r\nVuoi avere più informazioni su questo problema?",
path:"Percorso",
newdocument:"Sei sicuro di voler cancellare tutto il contenuto?",
toolbar_focus:"Vai a barra degli strumenti - Alt+Q, Vai all\'editor - Alt-Z, Vai a barra degli indirizzi - Alt-X",
more_colors:"Colori aggiuntivi"
});