<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Bem-vindo ao ";
$strUseMenu = "Use o menu ou clique nas liga&ccedil;&otilde;es diretas para come&ccedil;ar ";
$click_to_login = "Clique aqui para iniciar uma sess&atilde;o.";
$login_text = "Introduza o seu nome e senha de utilizador para in&iacute;ciar uma sess&atilde;o";
$login_username = "Utilizador";
$login_password = "Senha";
$login_missing_field = "Voc&ecirc; n&atilde;o introduziu o seu nome de utilizador ou senha.";
$login_bad_login = "Utilizador ou senha errada";
$login_remind = "Mantenha-me entrado at&eacute; eu indicar que quero sair e teclar 'disconex&atilde;o'.";
$login_language = 'Idioma';
?>