#!/bin/bash
set -e

# Use debconf.
. /usr/share/debconf/confmodule


db_get groupoffice-servermanager/wildcarddomain
wildcarddomain="$RET"

cat /etc/groupoffice/config-db.php > /etc/groupoffice/config-servermanager.inc.php
echo -e "\$wildcarddomain='$wildcarddomain';\n" >> /etc/groupoffice/config-servermanager.inc.php

chown root:www-data /etc/groupoffice/config-servermanager.inc.php
chmod 640 /etc/groupoffice/config-servermanager.inc.php



php /usr/share/groupoffice-servermanager/configure.php
php /usr/share/groupoffice-servermanager/installservermanager.php

a2enmod vhost_alias

chown -R www-data:www-data /home/govhosts

invoke-rc.d apache2 restart 3> /dev/null || true

#This will cause a permission error and installations will update automatically now so I disabled it.
#Group-Office automatically updates on first access anyway.
#php /usr/share/groupoffice-servermanager/upgradeinstallations.php

#DEBHELPER#

exit 0
