<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));

$sync_with = 'Synchronisiere mit:';
$sync_calendar = 'Kalender';
$sync_addressbook = 'Adressbuch';
$sync_server_is_master = 'Die Daten von Group-Office haben die höchste Priorität';
$sync_sync_private = 'Die privaten Termine ebenfalls synchronisieren';
$sync_devices = 'Geräte';

$sync_last_calendar_sync = 'Kalender zuletzt synchronisiert';
$sync_last_addressbook_sync = 'Adressbuch zuletzt synchronisiert';

$sync_never = 'Niemals';

//2.15
$sync_last_todos_sync = 'Letze Syncronisation der Aufgaben';
