<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));

$sync_with = 'Sincronizar com:';
$sync_calendar = 'Calendário';
$sync_addressbook = 'Agenda';
$sync_server_is_master = 'Dados de Group-Office são mais importantes que os dados do periférico convidado';
$sync_sync_private = 'Sincronizar também apontamentos privados';
$sync_devices = 'Periféricos';

$sync_last_calendar_sync = 'Última sincronização do calendário';
$sync_last_addressbook_sync = 'Última sincronização da agenda';

$sync_never = 'Nunca';

//2.15
$sync_last_todos_sync = 'Última sincronização de tarefas';
$sync_log='Registo de sincronizações';

//2.16
$sync_max_days_old = 'Sincronizações de compromissos mais recentes que';
$sync_days = 'dias';
$sync_delete_old_events='Apagar compromissos mais antigos que o tempo acima';
$sync_click_to_verify='Clique para verificar';

$sync_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=185';
