<?php
$name="opentts";
$language="english";
$tts_version="2.0.2-alpha";
$frameware="group-office";
$nuke_user_id_fieldname="id";
$nuke_username_fieldname="username";
$nuke_user_first_name_fieldname="first_name";
$nuke_user_last_name_fieldname="last_name";
$nuke_user_table="users";
$nuke_user_website="homepage";
$nuke_user_email_fieldname="email";
$hlpdsk_prefix="tts";
$shadow_dark='dcdcdc';
$shadow_light='ffffff';
$shadow_hidden='ffdfff';
$hlpdsk_email="support@riunx.com";
$hlpdsk_gmt_diff="+2";
$tts_demo="";
$rtl_dir="ltr";
$charset="windows-1255";
$hlpdsk_theme="Aqua";
$classes_dir="opentts";

?>
