<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('filesystem'));

$strLookIn = 'Look in';
$strType = "Type";
$strModified = "Modified";
$strCreated = "Created";
$strAccessed = "Accessed";
$strSize = "Size";
$fbRefresh = "Refresh";
$fbProperties = "Properties";
$fbNewFolder = "New folder";
$fbDelete = "Delete";
$fbCut = "Cut";
$fbPaste = "Paste";
$fbCopy = "Copy";
$fbFiletypes = "Filetypes";
$fbSharing = "Sharing";
$fbShares = "Shared folders";
$fbShare = "Shared folder";
$fbPath = "Path";
$fbFolders = "Folders";
$fbNoSelect = "You didn't select an item. Click on an icon next to the name to select an item.";
$fbConfirmDelete = "Confirm delete";
$fbWritePermissions = "Write permissions";
$fbReadPermissions = "Read permissions";
$fbGeneral = "General";
$fbConfirmOverwrite = "Confirm overwrite";
$strOverwritePrefix = "Are you sure you want to overwrite ";
$strOverwriteSuffix = "?";
$fbDescription = "Description";
$fbLocation = "Location";
$fbUpload = "Upload";
$fbUpload_text = "Select file to upload";
$fbUpload_nofile = "No file was not recieved.";
$fbVersions = "Versions";
$fbDelete_version = "Are you sure you want to delete this version?";
$fbFolderExists = "The folder already exists.";
$fbEmailFile = "E-mail file";
$fbFolder = "Folder";

$fbNoFile = "The file you tried to upload is too big.<br /> The maximum transferable filesize is set to: ";
$fbPleaseWait = "Please wait. Sending data...";
$fbFilename = "Filename";
$fbUpLevel = "Level up";
$fbItems = "item(s)";
$fbFolderSize = "Size of folder";
$fbMaxUploadSize = "Maximum size";
$ml_file_too_big = "The file you tried to attach is too big, the maximum filesize for attachments is set to: ";
$fbNoRightToOverwrite = "The file already exist and you do not have the right to overwrite it.";
$fbSaveFile = "Save File As...";
$fbNameExists = "The name already exists in this folder.";
$fbThis = 'this';
$fbFiles = 'Files';
$fs_activate_sharing = 'Activate sharing';
$fs_calculate_folder_size = 'Calculate folder size';
$fs_no_multi_select = 'U can\'t select more then one item with this option';
$fs_search = 'Search';
$search_title = "Search for files and folders";
$fs_keyword = 'Keyword';
$fs_enter_keyword = 'Please enter a keyword';
$fs_modified_before = 'Modified before';
$fs_modified_after = 'Modified after';

//translation required
$fb_compress='Compress';
$fb_decompress='Decompress';
$fb_failed_to_create = 'Failed to create archive.';
$fb_failed_to_extract = 'Failed to extract';
$fb_compression_type = 'Compression';
$fbFreeQuotaSpace = 'Free Space in your Directory';

//2.11
$fb_unkown_compression = 'Unknown compression type';
$fs_new_doc = 'New document';
$fs_cleanup = 'Cleanup HTML';
$fbMultipleFiles = 'Multiple files';
$fbSelect = "Select file"; //changed

//2.14
$fs_confirm_unshare = 'Are you sure you want to remove all permissions on this folder?';
$fs_users = 'Users';
$fs_personal = 'Personal';

$fs_inssufficient_diskspace = 'Insufficient disk space';

//2.15
$fs_open_containing_folder = 'Open containing folder';
$fs_file_put_in='The file  "%s" is uploaded to "%s"';
$fs_new_file_uploaded = 'New file uploaded: %s';

$fs_download = 'Download';
$fs_view = 'View';

$fs_notify = 'Send an e-mail if someone uploads a new file';


$fs_status='Status';
$fs_author='Author';
$fs_no_status_history='No status history';
$fs_no_status='None';
$fs_file_updated='File %s modified';
$fs_open_properties='Open properties window when a file is double clicked';
?>
