<?php
require_once($GO_LANGUAGE->get_fallback_language_file('filesystem'));

$strLookIn = 'Mirar en';
$strType = "Tipo";
$strModified = "Modificado";
$strCreated = "Creado";
$strAccessed = "Accedido";
$strSize = "Tamaño";
$fbRefresh = "Refrescar";
$fbProperties = "Propiedades";
$fbNewFolder = "Nueva carpeta";
$fbDelete = "Eliminar";
$fbCut = "Cortar";
$fbPaste = "Pegar";
$fbCopy = "Copiar";
$fbFiletypes = "Tipos de ficheros";
$fbSharing = "Compartiendo";
$fbShares = "Carpetas compartidas";
$fbShare = "Carpeta compartida";
$fbPath = "Ruta";
$fbFolders = "Carpetas";
$fbNoSelect = "No ha seleccionado ningún elemento. Haga click en el icono del nombre para seleccionar un elemento.";
$fbConfirmDelete = "Confirmar la eliminación";
$fbWritePermissions = "Permisos de escritura";
$fbReadPermissions = "Permisos de lectura";
$fbGeneral = "General";
$fbConfirmOverwrite = "Confirmar sobreescritura";
$strOverwritePrefix = "¿Está seguro que desea sobreescribir ";
$strOverwriteSuffix = "?";
$fbDescription = "Descripción";
$fbLocation = "Lugar";
$fbUpload = "Cargar";
$fbUpload_text = "Seleccionar fichero para cargar";
$fbUpload_nofile = "No se ha seleccionado ningún fichero.";
$fbVersions = "Versiones";
$fbDelete_version = "¿Está seguro que desea eliminar esta versión?";
$fbFolderExists = "La carpeta ya existe.";
$fbEmailFile = "Fichero de correo electrónico";
$fbFolder = "Carpeta";

$fbNoFile = "El fichero que ha intentado cargar es demasiado grande.<br /> El tamaño máximo permitido para la transferencia de ficheros es de: ";
$fbPleaseWait = "Espere por favor. Enviando datos...";
$fbFilename = "Nombre del fichero";
$fbUpLevel = "Subir un nivel";
$fbItems = "elementos(s)";
$fbFolderSize = "Tamaño de la carpeta";
$fbMaxUploadSize = "Tamaño máximo";
$ml_file_too_big = "El fichero que ha intentado adjuntar es demasiado grande, el tamaño máximo para los ficheros adjuntos es de: ";
$cmdSearch = "Buscar";
$fbNoRightToOverwrite = "El fichero ya existe y usted no tiene permisos para sobreescribir.";
$fbSaveFile = "Guardar el fichero como...";
$fbNameExists = "El nombre ya existe en esta carpeta.";
$fbThis = 'este';
$fbFiles = 'Ficheros';
$fs_activate_sharing = 'Activar compartición';
$fs_calculate_folder_size = 'Calcular el tamaño de la carpeta';
$fs_no_multi_select = 'No puede seleccionar más de un elemento con esta opción';
$fs_search = 'Buscar';
$search_title = "Buscar ficheros y carpetas";
$fs_keyword = 'Palabra clave';
$fs_enter_keyword = 'Por favor, introduzca una palabra clave';
$fs_modified_before = 'Modificado antes del';
$fs_modified_after = 'Modificado después del';

//translation required
$fb_compress='Compresión';
$fb_decompress='Descompresión';
$fb_failed_to_create = 'Ha fallado la creación del archivo.';
$fb_failed_to_extract = 'Ha fallado la extracción';
$fb_compression_type = 'Compresión';
$fbFreeQuotaSpace = 'Espacio libre en su directorio';

//2.11
$fb_unkown_compression = 'Tipo de compresión desconocido';
$fs_new_doc = 'Nuevo documento';
$fs_cleanup = 'Limpiar HTML';
$fbMultipleFiles = 'Múltiples ficheros';
$fbSelect = "Seleccionar fichero"; //changed

//2.14
$fs_confirm_unshare = '¿Está seguro que desea eliminar todos los permisos de esta carpeta?';
$fs_users = 'Usuarios';
$fs_personal = 'Personal';

$fs_inssufficient_diskspace = 'Espacio de disco insuficiente';
?>
