<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('filetypes'));

$ft_title = "Tipos de Ficheiros";
$ft_text = "Os Tipos de Ficheiros s&atilde;o automaticamente adicionados por Group-Office. You can change icons and names here.";

$ft_icon = "&Iacute;cone";
$ft_extension = "Sufixo";
$ft_friendly = "Nome amig&aacute;vel";
$ft_content = "Tipo de conte&uacute;do";
$ft_no_filetypes = "Nenhums tipos de ficheiros foram encontrados.";
$ft_upload_text = "Selecione o &iacute;cone que voc&ecirc; quer enviar para representar este tipo de ficheiro. Apenas ficheiros do tipo GIF s&atilde;o aceitados.";
$ft_no_file = "Nenhum ficheiro foi recebido.";
$ft_please_wait = "Por favor aguarde durante a fase de envio deste &iacute;cone...";
$ft_properties = "Propriedades";
$ft_filename = "Nome de Ficheiro";
$ft_current_icon = "&Iacute;cone atual";
?>
