<?php
require_once($GO_LANGUAGE->get_fallback_language_file('addressbook'));

//contacts
$contacts_title = "Livro de Endere&ccedil;os";
$contacts_no_contacts = "Nenhuns contatos encontrados.";
$contacts_members = "membros";
$contacts_contacts = "contatos";
$contacts_add = "Novo Contato";
$contacts_groups = "grupos";
$contacts_other = "Outros Contatos";
$contacts_move_to_group = "Mude os contatos selecionados para o grupo...";
$groups_no_groups = "Voc&ecirc; n&atilde;o tem nenhuns grupos";
$contacts_group = "grupo";
$contacts_empty_group = "Use o menu de lista para mudar contatos para este grupo.";
$contacts_this_group = 'este grupo';

$add_contacts_text = "Preencha o endere&ccedil;o E-mail do contato e o c&oacute;digo de autoriza&ccedil;&atilde;o e clique 'Ok'";
$add_contacts_success = "Utilizador adicionado com sucesso";
$add_contacts_wrong = "C&oacute;digo errado do email ou de autoriza&ccedil;&atilde;o";
$add_personal_text = "Clique sobre 'Guardar' para adicionar o contato. Os campos marcados com a * s&atilde;o requeridos.";
$contacts_select = "Selecione os contatos para adicionar e clique 'Ok'.";
$contacts_select_title = "Contatos";
$contact_profile = "Perfil do contato";
$user_profile = "Perfil do utilizador";
$contacts_authorise = "autoriza&ccedil;&atilde;o";
$contacts_add_member = "Adicione este membro a seus contatos";
$strConfirmSynchronise = "Isto atualizar&aacute; este contato com dados que o utilizador entrou. As vossas mudan&ccedil;as manuais ser&atilde;o perdidas. Certo que voc&ecirc; quer continuar?";
$contacts_import = "importar";
$contacts_export = "exportar";
$contacts_export_text = "Selecione o tipo de CSV que voc&ecirc; gostaria de criar..";
$contacts_delete = "suprimir";

$contacts_import_text = "Selecione um ficheiro de CSV e clique sobre 'Ok'";
$contacts_import_text_group = "Selecione um grupo e ficheiro de CSV. Clique sobre 'Ok'.";
$fbNoFile = "Nenhum ficheiro foi recebido";
$fbPleaseWait = "Por favor aguarde enquanto o ficheiro &eacute; enviado...";

$strNotIncluded = "N&atilde;o importe";
$contacts_import_feedback = "As seguintes colunas foram encontradas no seu ficheiro de CSV.<br />";
$contacts_import_feedback .= "Selecione o grupo que voc&ecirc; deseja importar ou criar automaticamente os grupos baseados numa coluna do ficheiro.<br />";
$contacts_import_feedback .= "Combine colunas correspondentes do Group-Office com as colunas do ficheiro e verifique que voc&ecirc; n&atilde;o seleciona a mesma coluna duas vezes.";
$contacts_separator = "Os valores s&atilde;o separados com";
$contacts_no_separator = "Voc&ecirc; n&atilde;o introduziu um car&aacute;ter de separa&ccedil;&atilde;o.";
$fbFilename = "Nome do ficheiro";
$contacts_import_title = "Importar of Livro de Endere&ccedil;os";
$contacts_import_success = "Ficheiro importado com sucesso";
$contacts_import_double = "Voc&ecirc; selecionou uma ou mais colunas duas vezes. Corrija isto e tente-o outra vez.";
$contacts_import_noname = 'Voc&ecirc; deve selecionar o campo relacionado nome';
$contacts_import_incompatible = "Formato incompat&iacute;vel de ficheiro.<br /><br />Um ficheiro tipo CSV &eacute; um ficheiro com valores separados por v&iacute;rgulas.";
$strMember = "Membro";
$contact_exist_warning = "<b>Nota:</b> EEste utilizador j&aacute; est&aacute; na sua lista de contatos.";
$contacts_add_to_group = "Adicione os utilizadors selecionados aos contatos do grupo...";
$contacts_add_to = "Adicione os utilizadors selecionados aos contatos";
$contacts_add_user = "adicionar";
$contacts_edit = "modificar";
$contacts_no_select = "Voc&ecirc; n&atilde;o selecionou nada";
$contacts_this_contact = "este contato";

$contacts_seperator_text = 'Valores separados por';
$contacts_quote = 'Valores inclu&iacute;dos por';
$contacts_clrf = 'Linhas terminadas por';
$contacts_auto_group = 'Automaticamente crie grupos por ficheiro';
$contacts_import_to_group = 'Importar ao grupo';

$contacts_search = 'pesquisar';
$cmdSearch = 'pesquisar';
$contacts_search_text = "Entre frase da busca e clique sobre 'pesquisar'. Voc&ecirc; pode usar * como um car&aacute;ter selvagem.";
$contacts_results = 'resultado(s)';

//translation required
$contacts_color = 'Cor';

$contacts_colors['black'] = 'Preto';
$contacts_colors['red'] = 'Vermelho';
$contacts_colors['green'] = 'Verde';
$contacts_colors['blue'] = 'Azul';
$contacts_colors['pink'] = 'Rosa';
$contacts_colors['orange'] = 'Laranga';
$contacts_colors['brown'] = 'Castanho';
