tinyMCE.addI18n('en.advanced',{
style_select:"Estilos",
font_size:"Dimensión carácter",
fontdefault:"Tipo de carácter",
block:"Formato",
paragraph:"Párrafo",
div:"Div",
address:"Dirección",
pre:"Preformateado",
h1:"Título 1",
h2:"Título 2",
h3:"Título 3",
h4:"Título 4",
h5:"Título 5",
h6:"Título 6",
blockquote:"Bloque de texto",
code:"Código",
samp:"Código de ejemplo",
dt:"Fecha límite ",
dd:"Descripción",
bold_desc:"Negrita (Ctrl+B)",
italic_desc:"Cursiva (Ctrl+I)",
underline_desc:"Subrayado (Ctrl+U)",
striketrough_desc:"Tachado",
justifyleft_desc:"Equipara a la izquierda",
justifycenter_desc:"Equipara al centro",
justifyright_desc:"Equipara a la derecha ",
justifyfull_desc:"Justificado",
bullist_desc:"Lista No Ordenada",
numlist_desc:"Lista ordenada",
outdent_desc:"Aumenta regreso",
indent_desc:"Diminuisci regreso",
undo_desc:"Anulla (Ctrl+Z)",
redo_desc:"Restablecerá (Ctrl+Y)",
link_desc:"Insertar / Modificar Enlace",
unlink_desc:"Eliminar Enlace",
image_desc:"Insertar / editar imagen",
cleanup_desc:"Limpieza de código",
code_desc:"Edición de HTML",
sub_desc:"Subíndice",
sup_desc:"Apex",
hr_desc:"Introduzca regla horizontal",
removeformat_desc:"Eliminar formato",
custom1_desc:"Escriba la descripción",
forecolor_desc:"Seleccione el color del texto",
backcolor_desc:"Seleccione el color de fondo",
charmap_desc:"Insertar el carácter",
visualaid_desc:"Establecer directrices / invisible",
anchor_desc:"Insertar / editar ancla",
cut_desc:"Cortar",
copy_desc:"Copiar",
paste_desc:"Pegar",
image_props_desc:"Propiedades de Imagen",
newdocument_desc:"Nuevo documento",
help_desc:"Ayuda",
blockquote_desc:"Bloque de texto",
clipboard_msg:"Copiar/Cortar/Pegar no está disponible en Mozilla y Firefox.\r\n¿Desea obtener más información acerca de este problema?",
path:"Ruta",
newdocument:"¿Estás seguro de que desea borrar todo el contenido?",
toolbar_focus:"Ir a la barra de herramientas - Alt + Q, Ir a la editor - Alt-Z, Ir a la barra de direcciones - Alt-X",
more_colors:"Colores adicionales"
});