/** 
 * French Translation v1.0
 * Author : Lionel JULLIEN
 * Date : September, 11 2008
 */

tinyMCE.addI18n('fr.advanced',{
style_select:"Styles",
font_size:"Taille de police",
fontdefault:"Police",
block:"Format",
paragraph:"Paragraphe",
div:"Div",
address:"Adresse",
pre:"Préformatté",
h1:"Titre 1",
h2:"Titre 2",
h3:"Titre 3",
h4:"Titre 4",
h5:"Titre 5",
h6:"Titre 6",
blockquote:"Bloc de citation",
code:"Code",
samp:"Example de code",
dt:"Définition - Terme ",
dd:"Définition - Description",
bold_desc:"Gras (Ctrl+B)",
italic_desc:"Italique (Ctrl+I)",
underline_desc:"Souligné (Ctrl+U)",
striketrough_desc:"Barré",
justifyleft_desc:"Aligner à gauche",
justifycenter_desc:"Aligner au centre",
justifyright_desc:"Aligner à droite",
justifyfull_desc:"Justifié",
bullist_desc:"Liste non ordonnée",
numlist_desc:"Liste ordonnée",
outdent_desc:"Désindenter",
indent_desc:"Indenter",
undo_desc:"Annuler (Ctrl+Z)",
redo_desc:"Refaire (Ctrl+Y)",
link_desc:"Insérer/Editer un lien",
unlink_desc:"Délier",
image_desc:"Insérer/Editer une image",
cleanup_desc:"Nettoyer le code",
code_desc:"Editer le code HTML",
sub_desc:"Indice",
sup_desc:"Exposant",
hr_desc:"Insérer une règle horizontale",
removeformat_desc:"Enlever le formattage",
custom1_desc:"Votre description personnalisée ici",
forecolor_desc:"Sélectionner la couleur du texte",
backcolor_desc:"Sélectionner la couleur du fond",
charmap_desc:"Insérer un caractères personnalisé",
visualaid_desc:"Basculer les guides/éléments invisibles",
anchor_desc:"Insérer/Editer une ancre",
cut_desc:"Couper",
copy_desc:"Copier",
paste_desc:"Coller",
image_props_desc:"Proprétés de l\'image",
newdocument_desc:"Nouveau document",
help_desc:"Aide",
blockquote_desc:"Bloc de citation",
clipboard_msg:"Copier/couper/coller n\'est pas disponible dans Firefox et Mozilla.\r\nVoulez-vous plus d\informations concernant ce problème ?",
path:"Chemin",
newdocument:"Etes-vous sûr de vouloir effacer tous le contenu ?",
toolbar_focus:"Aller aux boutons outils - Alt+Q, Aller à l\'éditeur - Alt-Z, Aller au chemin de l\'élement - Alt-X",
more_colors:"Plus de couleurs"
});