<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Benvingut a ";
$strUseMenu = "Utilitzeu el menú o feu clic a les dreceres de sota per començar ";
$click_to_login = "Cliqueu aquí per entrar.";
$login_text = "Introduïu el vostre nom d'usuari i la contrassenya per iniciar la sessió";
$login_username = "Nom d'usuari";
$login_password = "Contrassenya";
$login_missing_field = "No heu introduït el vostre nom d'usuari o la contrassenya.";
$login_bad_login = "Nom d'usuari o contrassenya incorrectes";
$login_remind = "Conserva la sessió fins que cliqui el botó de sortida.";
$login_language = 'Idioma';

//2.12
$login_register = 'o cliqueu %s per signar';
$login_here = "aquí";
$login_lost_password = 'contrassenya perduda?';
$login_lost_password_title = 'Recupera la contrassenya';
$login_lost_password_text= 'Si us plau, introduïu el vostre correu electrònic i se us enviarà una nova contrassenya a la vostra adreça.';
$login_lost_password_mail_body = "Heu demanat una nova contrassenya per en %s. Les vostres dades per entrar com a %s són:\n\nNom d'usuari: %s\nContrassenya: %s\n\nBona sort!";
$login_new_password = 'Nova contrassenya';
$login_lost_password_success = 'Ha estat enviada una nova contrassenya a en %s';
$login_lost_password_failed = 'Ho sento, l\'adreça de correu electrònic \'%s\' no està registrada a aquest sistema.';

//2.14
$login_fullscreen = $GO_CONFIG->title.' ha estat obert a pantalla completa per vostè automàticament. Podeu tancar la finestra o engegar Group-Office un altre cop.';
$login_start = 'Torna a començar';
?>
