<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));

$sync_with = 'Sincronizar con:';
$sync_calendar = 'Calendario';
$sync_addressbook = 'Libreta de direcciones';
$sync_server_is_master = 'Los datos de Group-Office son más importantes que los del dispositivo invitado';
$sync_sync_private = 'Sincronizar las citas privadas también';
$sync_devices = 'Dispositivos';

$sync_last_calendar_sync = 'Última sincronización de calendario';
$sync_last_addressbook_sync = 'Última sincronización de libreta de direcciones';

$sync_never = 'Nunca';
