<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('filetypes'));

$filetypes['unknown'] = 'Tipo de fichero desconocido';
$filetypes['txt'] = 'Fichero de texto';
$filetypes['sxw'] = 'Documento de OpenOffice.Org Writer';
$filetypes['doc'] = 'Documento de Microsoft Word';
$filetypes['xls'] = 'Hoja de cálculo de Microsoft Excel';
$filetypes['mdb'] = 'Base de datos de Microsoft Access';
$filetypes['ppt'] = $filetypes['pps'] = 'Presentación de Microsoft Powerpoint';
$filetypes['sxc'] = 'Hoja de cálculo de OpenOffice.Org Calc';
$filetypes['tar'] = 'Archivo Tar';
$filetypes['zip'] = 'Archivo comprimido ZIP';
$filetypes['rar'] = 'Archivo comprimido RAR';
$filetypes['gz'] = $filetypes['tgz'] = 'Archivo comprimido GZIP';
$filetypes['bz2'] = 'Archivo comprimido BZIP2'; 
$filetypes['pdf'] = 'Documento PDF';
$filetypes['exe'] = 'Fichero ejecutable de Windows';
$filetypes['ttf'] = 'Fuente de letra True type';
$filetypes['html'] = $filetypes['htm'] = 'Documento HTML';
$filetypes['jpg'] = $filetypes['jpeg'] = 'Imagen';
$filetypes['gif'] = 'Imagen';
$filetypes['bmp'] = 'Imagen';
$filetypes['tif'] = 'Imagen';
$filetypes['png'] = 'Imagen';
$filetypes['php'] = 'Script en PHP';
$filetypes['ics'] = 'Información de calendario';
$filetypes['vcf'] = 'Información de contacto';
$filetypes['wav'] = $filetypes['ogg'] = $filetypes['mp3'] = $filetypes['wma'] = 'Fichero de sonido';
$filetypes['mpg'] = $filetypes['mpeg'] = $filetypes['avi'] = $filetypes['wmv'] = $filetypes['wmf'] = 'Video clip';
$filetypes['pdf'] = 'Documento PDF de Adobe Acrobat';
$filetypes['doc'] = $filetypes['dot'] = 'Documento de Microsoft Word';
$filetypes['psd'] = 'Fichero de Adobe Photoshop';
$filetypes['rtf'] = 'Formato de Texto Enriquecido';
$filetypes['swf'] = 'Película en Macromedia Flash';
$filetypes['fla'] = 'Documento (fuente) en Macromedia Flash';
$filetypes['xls'] = $filetypes['xlt'] = 'Hoja de cálculo de Microsoft Excel';
$filetypes['ai'] = 'Fichero de Adobe Illustrator';
?>
