#!/bin/sh
set -e

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule
    # Remove my changes to the db.
    db_purge

		rm /etc/groupoffice/servermanager.inc.php
		rm /etc/apache2/sites-enabled/000-groupoffice
fi

#DEBHELPER#

exit 0
