<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));

$about_text = 'Group-Office ha estat creat per Intermesh. Per més informació visiteu <a class="normal" href="http://www.intermesh.nl">http://www.intermesh.nl</a>.';
$about_support = 'Disposeu de les següents opcions per rebre suport';

$about_pro_support = 'Suport Professional';
$about_com_support = 'Suport de la Comunitat';
$about_help_files = 'Fitxers d\'ajuda';
?>
