<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));
$about_text='Weitere Informationen erhalten Sie unter <a target="_blank" href="http://www.group-office.com/" class="normal">http://www.group-office.com</a>.';
$about_support='Für eine Unterstützung stehen folgende Optionen zur Verfügung';
$about_pro_support='Professionelle Unterstützung';
$about_com_support='Unterstützung durch die Community';
$about_help_files='Hilfe Dateien';
?>