<?php
$config['serverclient_server_url']="http://localhost/groupoffice/";
$config['serverclient_username']="admin";
$config['serverclient_password']="admin";
$config['serverclient_mbroot']="";
$config['serverclient_use_ssl']="0";
$config['serverclient_novalidate_cert']="0";
$config['serverclient_type']="imap";
$config['serverclient_host']="localhost";
$config['serverclient_port']="143";
$config['serverclient_smtp_host']="localhost";
$config['serverclient_smtp_port']="25";
$config['serverclient_smtp_encryption']="";
$config['serverclient_smtp_username']="";
$config['serverclient_smtp_password']="";
$config['phpMyAdminUrl']="";