/** 
 * Copyright Intermesh
 * 
 * This file is part of Group-Office. You should have received a copy of the
 * Group-Office license along with Group-Office. See the file /LICENSE.TXT
 * 
 * If you have questions write an e-mail to info@intermesh.nl
 * 
 * @version $Id: SelectCountry.js 2507 2008-07-14 14:05:13Z mschering $
 * @copyright Copyright Intermesh
 * @author Merijn Schering <mschering@intermesh.nl>
 */
  
GO.form.SelectCountry = function(config){
	
	var countries = [
		["AF", GO.lang.countries["AF"]],
		["AL", GO.lang.countries["AL"]],
		["DZ", GO.lang.countries["DZ"]],
		["AS", GO.lang.countries["AS"]],
		["AD", GO.lang.countries["AD"]],
		["AO", GO.lang.countries["AO"]],
		["AI", GO.lang.countries["AI"]],
		["AQ", GO.lang.countries["AQ"]],
		["AG", GO.lang.countries["AG"]],
		["AR", GO.lang.countries["AR"]],
		["AM", GO.lang.countries["AM"]],
		["AW", GO.lang.countries["AW"]],
		["AU", GO.lang.countries["AU"]],
		["AT", GO.lang.countries["AT"]],
		["AZ", GO.lang.countries["AZ"]],
		["BS", GO.lang.countries["BS"]],
		["BH", GO.lang.countries["BH"]],
		["BD", GO.lang.countries["BD"]],
		["BB", GO.lang.countries["BB"]],
		["BY", GO.lang.countries["BY"]],
		["BE", GO.lang.countries["BE"]],
		["BZ", GO.lang.countries["BZ"]],
		["BJ", GO.lang.countries["BJ"]],
		["BM", GO.lang.countries["BM"]],
		["BT", GO.lang.countries["BT"]],
		["BO", GO.lang.countries["BO"]],
		["BA", GO.lang.countries["BA"]],
		["BW", GO.lang.countries["BW"]],
		["BV", GO.lang.countries["BV"]],
		["BR", GO.lang.countries["BR"]],
		["IO", GO.lang.countries["IO"]],
		["BN", GO.lang.countries["BN"]],
		["BG", GO.lang.countries["BG"]],
		["BF", GO.lang.countries["BF"]],
		["BI", GO.lang.countries["BI"]],
		["KH", GO.lang.countries["KH"]],
		["CM", GO.lang.countries["CM"]],
		["CA", GO.lang.countries["CA"]],
		["CV", GO.lang.countries["CV"]],
		["KY", GO.lang.countries["KY"]],
		["CF", GO.lang.countries["CF"]],
		["TD", GO.lang.countries["TD"]],
		["CL", GO.lang.countries["CL"]],
		["CX", GO.lang.countries["CX"]],
		["CC", GO.lang.countries["CC"]],
		["CO", GO.lang.countries["CO"]],
		["KM", GO.lang.countries["KM"]],
		["CG", GO.lang.countries["CG"]],
		["CK", GO.lang.countries["CK"]],
		["CR", GO.lang.countries["CR"]],
		["CI", GO.lang.countries["CI"]],
		["HR", GO.lang.countries["HR"]],
		["CU", GO.lang.countries["CU"]],
		["CY", GO.lang.countries["CY"]],
		["CZ", GO.lang.countries["CZ"]],
		["DK", GO.lang.countries["DK"]],
		["DJ", GO.lang.countries["DJ"]],
		["DM", GO.lang.countries["DM"]],
		["DO", GO.lang.countries["DO"]],
		["TP", GO.lang.countries["TP"]],
		["EC", GO.lang.countries["EC"]],
		["EG", GO.lang.countries["EG"]],
		["SV", GO.lang.countries["SV"]],
		["GQ", GO.lang.countries["GQ"]],
		["ER", GO.lang.countries["ER"]],
		["EE", GO.lang.countries["EE"]],
		["ET", GO.lang.countries["ET"]],
		["FK", GO.lang.countries["FK"]],
		["FO", GO.lang.countries["FO"]],
		["FJ", GO.lang.countries["FJ"]],
		["FI", GO.lang.countries["FI"]],
		["FR", GO.lang.countries["FR"]],
		["FX", GO.lang.countries["FX"]],
		["GF", GO.lang.countries["GF"]],
		["PF", GO.lang.countries["PF"]],
		["TF", GO.lang.countries["TF"]],
		["GA", GO.lang.countries["GA"]],
		["GM", GO.lang.countries["GM"]],
		["GE", GO.lang.countries["GE"]],
		["DE", GO.lang.countries["DE"]],
		["GH", GO.lang.countries["GH"]],
		["GI", GO.lang.countries["GI"]],
		["GR", GO.lang.countries["GR"]],
		["GL", GO.lang.countries["GL"]],
		["GD", GO.lang.countries["GD"]],
		["GP", GO.lang.countries["GP"]],
		["GU", GO.lang.countries["GU"]],
		["GT", GO.lang.countries["GT"]],
		["GN", GO.lang.countries["GN"]],
		["GW", GO.lang.countries["GW"]],
		["GY", GO.lang.countries["GY"]],
		["HT", GO.lang.countries["HT"]],
		["HM", GO.lang.countries["HM"]],
		["HN", GO.lang.countries["HN"]],
		["HK", GO.lang.countries["HK"]],
		["HU", GO.lang.countries["HU"]],
		["IS", GO.lang.countries["IS"]],
		["IN", GO.lang.countries["IN"]],
		["ID", GO.lang.countries["ID"]],
		["IE", GO.lang.countries["IE"]],
		["IL", GO.lang.countries["IL"]],
		["IT", GO.lang.countries["IT"]],
		["JM", GO.lang.countries["JM"]],
		["JP", GO.lang.countries["JP"]],
		["JO", GO.lang.countries["JO"]],
		["KZ", GO.lang.countries["KZ"]],
		["KE", GO.lang.countries["KE"]],
		["KI", GO.lang.countries["KI"]],
		["KW", GO.lang.countries["KW"]],
		["KG", GO.lang.countries["KG"]],
		["LA", GO.lang.countries["LA"]],
		["LV", GO.lang.countries["LV"]],
		["LB", GO.lang.countries["LB"]],
		["LS", GO.lang.countries["LS"]],
		["LR", GO.lang.countries["LR"]],
		["LY", GO.lang.countries["LY"]],
		["LI", GO.lang.countries["LI"]],
		["LT", GO.lang.countries["LT"]],
		["LU", GO.lang.countries["LU"]],
		["MO", GO.lang.countries["MO"]],
		["MK", GO.lang.countries["MK"]],
		["MG", GO.lang.countries["MG"]],
		["MW", GO.lang.countries["MW"]],
		["MV", GO.lang.countries["MV"]],
		["ML", GO.lang.countries["ML"]],
		["MT", GO.lang.countries["MT"]],
		["MH", GO.lang.countries["MH"]],
		["MQ", GO.lang.countries["MQ"]],
		["MR", GO.lang.countries["MR"]],
		["MU", GO.lang.countries["MU"]],
		["YT", GO.lang.countries["YT"]],
		["MX", GO.lang.countries["MX"]],
		["FM", GO.lang.countries["FM"]],
		["MD", GO.lang.countries["MD"]],
		["MC", GO.lang.countries["MC"]],
		["MN", GO.lang.countries["MN"]],
		["MS", GO.lang.countries["MS"]],
		["MA", GO.lang.countries["MA"]],
		["MZ", GO.lang.countries["MZ"]],
		["MM", GO.lang.countries["MM"]],
		["NA", GO.lang.countries["NA"]],
		["NR", GO.lang.countries["NR"]],
		["NP", GO.lang.countries["NP"]],
		["NL", GO.lang.countries["NL"]],
		["AN", GO.lang.countries["AN"]],
		["NC", GO.lang.countries["NC"]],
		["NZ", GO.lang.countries["NZ"]],
		["NI", GO.lang.countries["NI"]],
		["NE", GO.lang.countries["NE"]],
		["NG", GO.lang.countries["NG"]],
		["NU", GO.lang.countries["NU"]],
		["NF", GO.lang.countries["NF"]],
		["MP", GO.lang.countries["MP"]],
		["NO", GO.lang.countries["NO"]],
		["OM", GO.lang.countries["OM"]],
		["PW", GO.lang.countries["PW"]],
		["PA", GO.lang.countries["PA"]],
		["PG", GO.lang.countries["PG"]],
		["PY", GO.lang.countries["PY"]],
		["PE", GO.lang.countries["PE"]],
		["PH", GO.lang.countries["PH"]],
		["PN", GO.lang.countries["PN"]],
		["PL", GO.lang.countries["PL"]],
		["PT", GO.lang.countries["PT"]],
		["PR", GO.lang.countries["PR"]],
		["QA", GO.lang.countries["QA"]],
		["RE", GO.lang.countries["RE"]],
		["RO", GO.lang.countries["RO"]],
		["RU", GO.lang.countries["RU"]],
		["RW", GO.lang.countries["RW"]],
		["KN", GO.lang.countries["KN"]],
		["LC", GO.lang.countries["LC"]],
		["VC", GO.lang.countries["VC"]],
		["WS", GO.lang.countries["WS"]],
		["SM", GO.lang.countries["SM"]],
		["ST", GO.lang.countries["ST"]],
		["SN", GO.lang.countries["SN"]],
		["SA", GO.lang.countries["SA"]],
		["SC", GO.lang.countries["SC"]],
		["SL", GO.lang.countries["SL"]],
		["SK", GO.lang.countries["SK"]],
		["SI", GO.lang.countries["SI"]],
		["SB", GO.lang.countries["SB"]],
		["SO", GO.lang.countries["SO"]],
		["ZA", GO.lang.countries["ZA"]],
		["GS", GO.lang.countries["GS"]],
		["ES", GO.lang.countries["ES"]],
		["LK", GO.lang.countries["LK"]],
		["SH", GO.lang.countries["SH"]],
		["PM", GO.lang.countries["PM"]],
		["SD", GO.lang.countries["SD"]],
		["SR", GO.lang.countries["SR"]],
		["SJ", GO.lang.countries["SJ"]],
		["SZ", GO.lang.countries["SZ"]],
		["SE", GO.lang.countries["SE"]],
		["CH", GO.lang.countries["CH"]],
		["SY", GO.lang.countries["SY"]],
		["TW", GO.lang.countries["TW"]],
		["TJ", GO.lang.countries["TJ"]],
		["TZ", GO.lang.countries["TZ"]],
		["TG", GO.lang.countries["TG"]],
		["TK", GO.lang.countries["TK"]],
		["TO", GO.lang.countries["TO"]],
		["TT", GO.lang.countries["TT"]],
		["TN", GO.lang.countries["TN"]],
		["TR", GO.lang.countries["TR"]],
		["TM", GO.lang.countries["TM"]],
		["TC", GO.lang.countries["TC"]],
		["TV", GO.lang.countries["TV"]],
		["UG", GO.lang.countries["UG"]],
		["UA", GO.lang.countries["UA"]],
		["GB", GO.lang.countries["GB"]],
		["US", GO.lang.countries["US"]],
		["UM", GO.lang.countries["UM"]],
		["UY", GO.lang.countries["UY"]],
		["UZ", GO.lang.countries["UZ"]],
		["VU", GO.lang.countries["VU"]],
		["VA", GO.lang.countries["VA"]],
		["VE", GO.lang.countries["VE"]],
		["VG", GO.lang.countries["VG"]],
		["VI", GO.lang.countries["VI"]],
		["WF", GO.lang.countries["WF"]],
		["EH", GO.lang.countries["EH"]],
		["YE", GO.lang.countries["YE"]],
		["YU", GO.lang.countries["YU"]],
		["ZR", GO.lang.countries["ZR"]],
		["ZM", GO.lang.countries["ZM"]],
		["ZW", GO.lang.countries["ZW"]]
		];
	
	Ext.apply(this, config);

	GO.form.SelectCountry.superclass.constructor.call(this,{
   store: new Ext.data.SimpleStore({
        fields: ['iso', 'name'],
        data : countries        
    }),
		valueField: 'iso',
		displayField: 'name',
		triggerAction: 'all',
		editable: true,
		mode:'local',
		selectOnFocus:true,
		forceSelection: true,
		emptyText: GO.lang.strNoCountrySelected
	});

}
 
Ext.extend(GO.form.SelectCountry, Ext.form.ComboBox);