<?php
require_once($GO_LANGUAGE->get_fallback_language_file('filesystem'));

$strLookIn = 'Mira dins';
$strType = "Tipus";
$strModified = "Modificat";
$strCreated = "Creat";
$strAccessed = "Accedit";
$strSize = "Mida";
$fbRefresh = "Refresca";
$fbProperties = "Propietats";
$fbNewFolder = "Nova carpeta";
$fbDelete = "Suprimeix";
$fbCut = "Talla";
$fbPaste = "Enganxa";
$fbCopy = "Copia";
$fbFiletypes = "Tipus de fitxers";
$fbSharing = "En compartir";
$fbShares = "Carpetes compartides";
$fbShare = "Carpeta compartida";
$fbPath = "Camí";
$fbFolders = "Carpetes";
$fbNoSelect = "No heu seleccionat cap element. Feu clic a la icona del nom per seleccionar un element.";
$fbConfirmDelete = "Confirma la supressió";
$fbWritePermissions = "Permisos d'escriptura";
$fbReadPermissions = "Permisos de lectura";
$fbGeneral = "General";
$fbConfirmOverwrite = "Confirma sobreescriure";
$strOverwritePrefix = "Esteu segurs que voleu sobreescriure ";
$strOverwriteSuffix = "?";
$fbDescription = "Descripció";
$fbLocation = "Lloc";
$fbUpload = "Carrega";
$fbUpload_text = "Seleccioneu el fitxer a carregar";
$fbUpload_nofile = "No s'ha rebut cap fitxer.";
$fbVersions = "Versions";
$fbDelete_version = "Esteu segurs que voleu suprimir aquesta versió?";
$fbFolderExists = "La carpeta ja existeix.";
$fbEmailFile = "Fitxer de correu electrònic";
$fbFolder = "Carpeta";

$fbNoFile = "El fitxer que heu triat per carregar és massa gran.<br /> La mida màxima permesa per fitxer és de: ";
$fbPleaseWait = "Espereu si us plau. S'estan enviant les dades...";
$fbFilename = "Nom del fitxer";
$fbUpLevel = "Puja un nivell";
$fbItems = "elements(s)";
$fbFolderSize = "Mida de la carpeta";
$fbMaxUploadSize = "Mida màxima";
$ml_file_too_big = "El fitxer que heu provat d'adjuntar és massa gran, la mida màxima permesa pels fitxers adjunts és de: ";
$cmdSearch = "Cerca";
$fbNoRightToOverwrite = "El fitxer ja existeix i no teniu permisos per sobreescriure-hi.";
$fbSaveFile = "Desa el fitxer com a...";
$fbNameExists = "El nom ja existeix en aquesta carpeta.";
$fbThis = 'aquest';
$fbFiles = 'Fitxers';
$fs_activate_sharing = 'Activa la compartició';
$fs_calculate_folder_size = 'Calcula la mida de la carpeta';
$fs_no_multi_select = 'No podeu seleccionar més d\'un element amb aquesta opció';
$fs_search = 'Cerca';
$search_title = "Cerca fitxers i carpetes";
$fs_keyword = 'Paraula clau';
$fs_enter_keyword = 'Si us plau introduïu una paraula clau';
$fs_modified_before = 'Modificat abans de';
$fs_modified_after = 'Modificat després de';

//translation required
$fb_compress='Comprimeix';
$fb_decompress='Descomprimeix';
$fb_failed_to_create = 'Ha fallat la creació de l\'arxiu.';
$fb_failed_to_extract = 'No s\'ha pogut extreure';
$fb_compression_type = 'Compressió';
$fbFreeQuotaSpace = 'Espai lliure en el vostre directori';

//2.11
$fb_unkown_compression = 'Tipus de compressió desconeguda';
$fs_new_doc = 'Nou document';
$fs_cleanup = 'Neteja HTML';
$fbMultipleFiles = 'Múltiples fitxers';
$fbSelect = "Selecciona el fitxer"; //changed

//2.14
$fs_confirm_unshare = 'Esteu segurs de voler suprimir tots els permisos d\'aquesta carpeta?';
$fs_users = 'Usuaris';
$fs_personal = 'Personal';

$fs_inssufficient_diskspace = 'Espai de disc insuficient';
?>
