<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Idioma";
$pref_theme = "Tema";
$pref_date_format = "Format de la data";
$pref_thousands_seperator = "Separador de milers";
$pref_decimal_seperator = "Separador decimal";
$pref_mail_client = "Utilitza el client de correu electrònic de Group-Office per enviar missatges.";
$pref_look = "Aparença";
$pref_notations = "Paràmetres regionals";
$pref_currency = 'Moneda';
$pref_region_code = 'Regió';
$pref_max_rows_list = 'Número màxim de files a les llistes';
$pref_unlimited = 'Ilimitat';
$pref_timezone = 'Fus horari';
$pref_time_format = "Format de l'hora";
$pref_startmodule = 'Comença en el mòdul';

//2.01
$pref_first_weekday = 'Primer dia de la setmana';

//2.05
$adjust_to_dst = 'Canvia l\'hora d\'Estiu/Hivern automàticament';

//2.08
$pref_name_order = 'Ordena noms per';

//2.14
$pref_use_checkbox_select = 'Selecciona múltiples files sense fer servir la tecla CTRL';
?>
