<?php

$images['unknown_module']='22x22/gnome-windows.png';
$images['unknown_link_type']='16x16/gnome-windows.png';

$images['help']='16x16/icon-help.png';
$images['configuration']='16x16/administration.png';
$images['logout']='16x16/gnome-logout.png';
$images['search']='16x16/icon-search.png';

$images['add']='16x16/gtk-add.png';
$images['delete']='16x16/gtk-delete.png';
$images['close']='16x16/gtk-close.png';
$images['save']='16x16/gtk-save.png';

$images['link']='16x16/connect_established.png';
$images['unlink']='16x16/stock-disconnect.png';

$images['search_addressbook'] = '16x16/search_addressbook.png';

//for the old Group-Office datatable
$images['arrow_down']		= '16x16/arrow_down.gif';
$images['arrow_up']		= '16x16/arrow_up.gif';

//used in fixpng script for IE<7
$images['blank']		= '16x16/blank.gif';
