<table border="0" cellspacing="10" cellpadding="0">
<tr>
  <td align="center" nowrap>
    <a class="small" href="<?php echo $_SERVER['PHP_SELF']; ?>"><img src="<?php echo $GO_THEME->images['news']; ?>" border="0" height="32" width="32" /><br /><?php echo "&Uuml;bersicht"; ?></a></td>
  <td align="center" nowrap>
    <a class="small" href="<?php echo $_SERVER['PHP_SELF']; ?>?task=new_message"><img src="<?php echo $GO_THEME->images['compose']; ?>" border="0" height="32" width="32" /><br /><?php echo "Neue Nachricht"; ?></a></td>
</tr>
</table>
