<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('calendar'));

$sc_title = 'Nadpis';
$sc_description = 'Popis';
$sc_participants = 'Pozvaní';

$sc_location = 'Místo';

$month_times[0] = 'první';
$month_times[1] = 'druhý';
$month_times[2] = 'třetí';
$month_times[3] = 'čtvrtý';

$sc_new_app = 'Nová údálost';
$sc_calendars = 'Kalendáře';
$sc_invited = 'Jste pozváni na níže uvedenou údálost.';

$sc_types1[0] = 'bez opakování';
$sc_types1[1] = 'denně';
$sc_types1[2] = 'týdně';
$sc_types1[3] = 'měsíčně podle data';
$sc_types1[4] = 'mesíčně podle dne';
$sc_types1[5] = 'ročně';


$sc_types[0] = 'Jednou';
$sc_types[1] = 'Denně';
$sc_types[2] = 'Týdně';
$sc_types[3] = 'Měsíčně podle data';
$sc_types[4] = 'Měsíčně podle dne';
$sc_types[5] = 'Ročně';


$sc_start_at = 'Začátek';
$sc_end_at = 'Konec';
$sc_start_time = 'Začátek';
$sc_end_time = 'Konec';

$sc_at_days = 'Ve dnech';
$sc_of_month = 'měsíce.';

$sc_cycle_start = 'Období začíná v';
$sc_cycle_end = 'Opakovat do';
$sc_accept_question = 'Přejete si akceptovat a naplánovat tuto údálost?';

$sc_accept = 'přijmout';
$sc_decline = 'nepřijmout';

$sc_notime = 'celé dny';
$sc_noend = 'žádné konečné datum.';

$sc_never_happens = 'Špatné zadání! Tato událost se nikdy nestala.';
$sc_start_later = 'Špatné zadání! Začátek je zadán později než konec.';

$sc_add_self = 'Ruční zadání';

$sc_select_calendar = 'Vyberte kalendář a naplánujte událost';
$sc_accept_confirm = 'Událost je přijata a naplánována.';
$sc_no_calendars = 'Žádný platný kalendář nebyl nenalezen a událost nebyla nenaplánována.';
$sc_bad_event = 'Žádná platná událost nebyla nenalezena. Tato událost je pravděpodobně smazána.';
$sc_accept_title = 'Akceptovat událost';

$sc_decline_confirm = 'Událost nepřijata.';
$sc_decline_title = 'Nepřijmout událost';

$sc_status = 'Postavení';
$sc_not_responded = 'Nezodpovězeno';
$sc_accepted = 'Přijatá';
$sc_declined = 'Nepřijatá';
$sc_no_participants = 'Žádní účastníci';

$sc_person = 'Osoba';
$sc_owner = 'Vlastník';
$sc_type = 'Typ';
$sc_subscribed = 'Zapsáno';

$sc_subscribe = 'Zapsání se';
$sc_new_calendar = 'Nový kalendář';
$sc_no_calendar = 'Žádný kalendář nebyl nalezen. Prosím vytvořte jej nyní nebo jej Group-Office pro Vás automaticky vytvoří.';
$sc_day_view = 'Den';
$sc_week_view = 'Týden';
$sc_list_view = 'Seznam';
$sc_put_in = 'Uložit událost do';
$sc_inherit_permissions ='Zdědit práva po';
$sc_no_inherit = 'Nedědit';

$sc_select_calendar_please = 'Prosím, vyberte nejméně jeden kalendář.';
$sc_events = 'Události';

$sc_from_calendar = 'z kalendáře';
$sc_enitrely = 'Úplně';
$sc_delete_event = 'Odstranit událost';
$sc_delete_pre = 'Chcete událost odstranit';
$sc_delete_suf = 'úplně nebo jen z tohoto kalendáře?';

$sc_refresh = 'Obnovit';
$sc_reminder = 'Připomenout';
$sc_mins = 'minut';
$sc_hour = 'hodina';
$sc_hours = 'hodiny';
$sc_day = 'den';
$sc_days = 'dny/í';
$sc_week = 'týden';
$sc_weeks = 'týdny';
$sc_reminder_set_to_early = 'Připomínka se nemůže objevovat bez předchozího výskytu. Prosím zkraťte čas připomínky nebo prodlužte opakující se dobu.';
$sc_cycle_start_later = 'Začátek období je pozdější nebo roven datu konce.';


$cmdGenerate = 'Vytvořit';
$sc_preferences = 'Vlastnosti';
$sc_holidays = 'Svátky';

$strNoHolidays = 'Žádné svátky v databázi';
$strUnknown = 'Neznámý';
$strYear = 'Rok';
$strDeleteHolidaysPrefix = 'Jste si jistý, že chcete odstranit všechny prázdninové záznamy toho roku';
$strDeleteHolidaysSuffix = '?';
$strReplaceHolidays = 'Jste si jistý, že chcete přepsat všechny existující prázdninové záznamy?';
$sc_holidays_text1 = 'Prosím klikněte na \''.$cmdGenerate.'\' pro výpočet  svátků ve vybraném roce.';
$sc_holidays_text2 = 'Prosím klikněte na \''.$cmdApply.'\' pro uložení všech spočítaných svátků v databázi.';

//translation required below this
$sc_client = 'Klient';
$sc_no_contact = 'Žádný';

$sc_background = 'Barva pozadí';

$sc_colors['red'] = 'Červený';
$sc_colors['green'] = 'Zelený';
$sc_colors['blue'] = 'Modrý';
$sc_colors['pink'] = 'Růžový';
$sc_colors['orange'] = 'Oranžový';
$sc_colors['brown'] = 'Hnědý';
$sc_colors['yellow'] = 'Žlutý';
$sc_colors['grey'] = 'Šedý';
$sc_colors['purple'] = 'Nachový';
$sc_colors['white']= 'Bílý';
$sc_status = 'Stav';

$sc_show_hours = 'Zobrazovat hodiny od';
$sc_to = 'do';

$sc_today = 'Dnes';

$sc_recur_every = 'Opakování události';

$sc_private_event = 'Soukromá událost';
$sc_calendar_exists = 'Kalendář s tímto jménem již existuje';
//translate
$sc_month = 'měsíc';
$sc_view = 'Zobrazení';
$sc_calendar = 'Kalendář';
$sc_default = 'Výchozí';
$sc_month_view = 'Měsíc';

//text changed, needs new translation
$sc_holidays_no_file_prefix = 'Svátky nemohou být vytvořeny, protože soubor obsahující informace o svátcích pro jazyk ';
$sc_holidays_no_file_suffix = ' je prázdný nebo nebyl nalezen.';

$sc_no_events = 'Nenalezena žádná událost.';

//2.03
$cal_export = 'Export';
$cal_import = 'Import';
$cal_please_wait = 'Prosím čekejte...';
$cal_import_text = 'Vyber iCal ( *.ics ) soubor a klikni na "Ok"';
$cal_filename = 'Soubor';
$cal_import_success = 'Data importována';

//2.04
$cal_add_todo = 'Nový úkol';
$cal_todos = 'Úkol';

$cal_hide_completed = 'Schovat dokončené';
$cal_show_all = 'Zobrazit všechny úkoly';
$cal_show_own = 'Zobrazit vlastní úkoly';
$cal_show_responsible = 'Zobrazit přidělené úkoly';

$cal_priority = 'Priorita';
$cal_priority_values[0] = 'Malá';
$cal_priority_values[1] = 'Střední';
$cal_priority_values[2] = 'Velká';

$cal_status = 'Stav';
$cal_canceled = 'Zrušeno';
$cal_completed = 'Dokončeno na';
$cal_percent_completed = '% hotovo';

$cal_before_task_start = 'Dříve než se by se měl úkol spustit';
$cal_before_task_due = 'Dřívež by měl být úkol dokončen';
$cal_responsible = 'Přiděleno';
$cal_due_at = 'Termín';
$cal_no_todos= 'Žádné úkoly nenalezeny';
$cal_resend_invitation = 'Znovu zaslat pozvánku';

//2.05
$cal_everybody_write = 'Každý může měnit tuto událost';
$cal_everybody_read = 'Pouze já mohu měnit tuto událost';

$cal_view = 'Zobrazení';
$cal_views = 'Zobrazení';
$sc_view_exists = 'Zobrazení s tímto jménem už existuje.';
$cal_new_view = 'Nové zobrazení';
$cal_event_calendars = 'Kalendář(e)';

//2.06
$cal_view_merged = 'sloučeně';
$cal_view_emerged = 'odděleně';

//2.07
$cal_display = 'Zobrazit';
$sc_new_task = "Nový úkol";
$sc_all_day_events = 'události pro všechny dny';
$sc_all_day_event = 'událost pro všechny dny';
$sc_usual_events = 'události';
$sc_usual_event = 'událost';

//2.08
$sc_recur_section = 'Opakování';
$sc_options_section = 'Možnosti';
$sc_close = 'Zavřít';

$cal_count_single = 'událost';
$cal_count_multiple = 'události';

$cal_until = 'dokud';
$cal_forever = 'navždy';

//2.09
$cal_merged_overview = 'Sloučený přehled';
$cal_own_availability = 'Vlastní dostupnost';

//2.11
$cal_no_file = 'Nebyl přijat žádný soubor';
$cms_no_calendars_in_view = 'Nelze nic ukázat, protože ve zvoleném zobrazení není žádný kalendář. Klikněte na \'Zobrazení\' a nastavte jej.';
$cal_no_reminder = 'Bez budíku';

//2.13
$cal_refresh_rate = 'Frekvence obnovování';
$sc_seconds = 'sekund (Prázdná hodnota zakáže obnovování)';
$cal_default_reminder = 'Standardní budík';

// extra
$sc_months = 'měsíce';
?>
