#!/bin/sh
set -e

. /usr/share/debconf/confmodule

. /usr/share/dbconfig-common/dpkg/postinst.mysql
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_generate_include=php:/etc/groupoffice/config-db.php
dbc_go groupoffice-com $@

#for testing
if [ ! -e /usr/share/groupoffice ]; then
	ln -s /var/www/community/trunk/www /usr/share/groupoffice
fi

invoke-rc.d apache2 reload > /dev/null || true


php /usr/share/groupoffice-install-scripts/configure.php

#cache dir is touched by root by this process
if [ -e /home/groupoffice/cache ]; then
	chown -R www-data:www-data /home/groupoffice/cache
else
	chown -R www-data:www-data /home/groupoffice
fi

#DEBHELPER#

exit 0

