#!/bin/sh
set -e

. /usr/share/debconf/confmodule

. /usr/share/dbconfig-common/dpkg/postinst.mysql
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_generate_include=php:/etc/groupoffice/config-db.php
dbc_go groupoffice-com $@

#for testing
#if [ ! -e /usr/share/groupoffice ]; then
#	ln -s /var/www/community/trunk/www /usr/share/groupoffice
#fi

invoke-rc.d apache2 reload > /dev/null || true

php /usr/share/groupoffice-install-scripts/configure.php

#DEBHELPER#

exit 0

