<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('filetypes'));

$filetypes['unknown'] = 'Tipus de fitxer desconegut';
$filetypes['txt'] = 'Fitxer de text';
$filetypes['sxw'] = 'Document d\'OpenOffice.Org Writer';
$filetypes['doc'] = 'Document de Microsoft Word';
$filetypes['xls'] = 'Full de càlcul de Microsoft Excel';
$filetypes['mdb'] = 'Base de dades de Microsoft Access';
$filetypes['ppt'] = $filetypes['pps'] = 'Presentació de Microsoft Powerpoint';
$filetypes['sxc'] = 'Full de càlcul d\'OpenOffice.Org Calc';
$filetypes['tar'] = 'Arxiu Tar';
$filetypes['zip'] = 'Arxiu comprimit ZIP';
$filetypes['rar'] = 'Arxiu comprimit RAR';
$filetypes['gz'] = $filetypes['tgz'] = 'Arxiu comprimit GZIP';
$filetypes['bz2'] = 'Arxiu comprimit BZIP2'; 
$filetypes['pdf'] = 'Document PDF';
$filetypes['exe'] = 'Fitxer executable de Windows';
$filetypes['ttf'] = 'Font de lletra True type';
$filetypes['html'] = $filetypes['htm'] = 'Document HTML';
$filetypes['jpg'] = $filetypes['jpeg'] = 'Imatge';
$filetypes['gif'] = 'Imatge';
$filetypes['bmp'] = 'Imatge';
$filetypes['tif'] = 'Imatge';
$filetypes['png'] = 'Imatge';
$filetypes['php'] = 'Script en PHP';
$filetypes['ics'] = 'Informació de calendari';
$filetypes['vcf'] = 'Informació de contacte';
$filetypes['wav'] = $filetypes['ogg'] = $filetypes['mp3'] = $filetypes['wma'] = 'Fitxer de so';
$filetypes['mpg'] = $filetypes['mpeg'] = $filetypes['avi'] = $filetypes['wmv'] = $filetypes['wmf'] = 'Video clip';
$filetypes['pdf'] = 'Document PDF d\'Adobe Acrobat';
$filetypes['doc'] = $filetypes['dot'] = 'Document de Microsoft Word';
$filetypes['psd'] = 'Fitxer d\'Adobe Photoshop';
$filetypes['rtf'] = 'Format de Text Enriquit';
$filetypes['swf'] = 'Pel·lícula en Macromedia Flash';
$filetypes['fla'] = 'Document (font) en Macromedia Flash';
$filetypes['xls'] = $filetypes['xlt'] = 'Full de càlcul de Microsoft Excel';
$filetypes['ai'] = 'Fitxer d\'Adobe Illustrator';
?>
