<?php

// LANG: "fr", ENCODING: UTF-8
// Author: A. Kermorvant : armek@akserver.dyndns.org
// 24 Oct 2004

// FOR TRANSLATORS:
//
//   1. PLEASE PUT YOUR CONTACT INFO IN THE ABOVE LINE
//      (at least a valid email address)
//
//   2. PLEASE TRY TO USE UTF-8 FOR ENCODING;
//      (if this is not possible, please include a comment
//       that states what encoding is necessary.)

require_once($GO_LANGUAGE->get_fallback_base_language_file('filetypes'));

$ft_title = "Types de fichiers";
$ft_text = "Les types de fichiers sont automatiquement ajouté par Group-Office. Vous pouvez changer les icones et les noms içi.";

$ft_icon = "Icone";
$ft_extension = "Extension";
$ft_friendly = "Surnom";
$ft_content = "Type de contenu";
$ft_no_filetypes = "Pas de type de fichiers trouvés.";
$ft_upload_text = "Choisissez l'icone du type de fichier à charger. Seuls les fichiers GIF sont acceptés.";
$ft_no_file = "Aucun fichier reçu.";
$ft_please_wait = "Patientez pendant que l'icone est téléchargé..";
$ft_properties = "Propriétés";
$ft_filename = "Nom de fichier";
$ft_current_icon = "Icone en cours";
?>