<?php
// French Translation by RUSSO Bruno
//require_once($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'Bienvenue dans';
$sum_you_have = 'Vous avez';
$sum_new_messages = 'messages <b>non lus</b>';
$sum_new_message = 'message <b>non lu</b>';
$sum_no_new_mail = 'Aucun nouveau message';

$sum_manage_announcements = 'Gérer les annonces';
$sum_announcements_count = 'Annonces';
$sum_announcements_count_single = 'Annonce';
$sum_no_announcements = 'Aucune annonce trouvée';
$sum_due_time = 'Montrer jusqu\'à';
$sum_new_announcement = 'Nouvelle annonce';
$sum_private = 'Privée';

//2.10
$sum_today = 'Aujourd\'hui';
$sum_tommorow = 'Demain';
