#!/bin/sh

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule
    # Remove my changes to the db.
    db_purge

		rm /etc/postfix/mysql_virtual_alias_maps.cf
		rm /etc/postfix/mysql_virtual_domains_maps.cf
		rm /etc/postfix/mysql_virtual_mailbox_limit_maps.cf
		rm /etc/postfix/mysql_virtual_mailbox_maps.cf
		rm /etc/postfix/mysql_virtual_transports.cf
		rm /etc/postfix/mysql_relay_domains_maps.cf
		rm /etc/postfix/transport
		rm /etc/dovecot/dovecot-sql.conf
		rm /etc/groupoffice/vacation.pl
		rm /etc/groupoffice/globalconfig.inc.php
		rm /etc/groupoffice/config-mailserver.inc.php
fi


