<div align="center"><h1>{$maintitle}</h1></div>
{if $package == "go-hidden"}
  <b>phpThumb</b><br />
  <i>phpThumb creates thumbnails</i><br />
  <a href='http://phpthumb.sourceforge.net/demo/docs/phpthumb.readme.txt' target='_blank'>phpThumb Documentation</a><br /><br />
  <b>Swift</b><br />
  <i>Swift mails</i><br />
  <a href='http://www.swiftmailer.org/wikidocs/' target='_blank'>Swift Documentation</a><br />
{else}
  <b>Documentation of {$package} package</b><br />
  <br />
  This documentation was generated by <a href="{$phpdocwebsite}">phpDocumentor v{$phpdocversion}</a><br />
{/if}

