#!/bin/sh
set -e

# Use debconf.
. /usr/share/debconf/confmodule


echo Configuring Postfix

touch /etc/postfix/main.cf
cp /etc/postfix/main.cf /etc/postfix/main.cf.gobak.$2

#postconf -e 'recipient_delimiter = +'
#postconf -e 'inet_interfaces = all'
postconf -e 'mydestination = $myhostname, localhost, localhost.localdomain'
postconf -e 'proxy_read_maps = $local_recipient_maps $mydestination $virtual_alias_maps $virtual_alias_domains $virtual_mailbox_maps $virtual_mailbox_domains $relay_recipient_maps $relay_domains $canonical_maps $sender_canonical_maps $recipient_canonical_maps $relocated_maps $transport_maps $mynetworks $virtual_mailbox_limit_maps'
postconf -e 'virtual_alias_domains ='
postconf -e 'virtual_alias_maps = proxy:mysql:$config_directory/mysql_virtual_alias_maps.cf'
postconf -e 'virtual_mailbox_domains = proxy:mysql:$config_directory/mysql_virtual_domains_maps.cf'
postconf -e 'virtual_mailbox_maps = proxy:mysql:$config_directory/mysql_virtual_mailbox_maps.cf'
postconf -e 'virtual_mailbox_base = /home/vmail'
postconf -e 'virtual_minimum_uid = 150'
postconf -e 'virtual_uid_maps = static:150'
postconf -e 'virtual_gid_maps = static:8'
postconf -e 'virtual_create_maildirsize = yes'
postconf -e 'virtual_mailbox_extended = yes'
postconf -e 'virtual_mailbox_limit_maps = proxy:mysql:/etc/postfix/mysql_virtual_mailbox_limit_maps.cf'
postconf -e 'virtual_mailbox_limit_override = yes'
postconf -e 'virtual_maildir_limit_message = "The user you are trying to reach has exceeded their quota."'
postconf -e 'virtual_overquota_bounce = yes'
postconf -e 'transport_maps = proxy:mysql:/etc/postfix/mysql_virtual_transports.cf'
postconf -e 'smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_non_fqdn_hostname, reject_non_fqdn_sender, reject_non_fqdn_recipient, reject_unauth_destination, reject_unauth_pipelining, reject_invalid_hostname, reject_unknown_sender_domain, reject_rbl_client zen.spamhaus.org, reject_rbl_client list.dsbl.org, reject_rhsbl_sender dsn.fc-ignorant.org, permit'
postconf -e 'smtpd_data_restrictions = reject_unauth_pipelining, reject_multi_recipient_bounce, permit'


#check if user vmail exists
if  ! id vmail 1>/dev/null 2>&1 ; then
	echo Adding vmail user
	useradd -r -u 150 -g mail -d /home/vmail -s /sbin/nologin -c "Virtual Mailbox" vmail

	chmod 770 /home/vmail
	chown -R vmail:mail /home/vmail
fi


echo setting up dovecot
chmod 600 /etc/dovecot/*.conf
chown vmail /etc/dovecot/*.conf

#check if user vacation exists. Exit code 0 means it exists
if  ! id vacation 1>/dev/null 2>&1 ; then
then
	echo setting up vacation
	mkdir /var/spool/vacation
	useradd -r -d /var/spool/vmail -s /sbin/nologin -c "Virtual vacation" vacation
fi

chown -R vacation:vacation /var/spool/vacation/
chmod 700 /var/spool/vacation/
touch /var/log/vacation.log /var/log/vacation-debug.log
chown vacation:vacation /var/log/vacation*

chown vacation:vacation /usr/bin/vacation
chmod 700 /usr/bin/vacation

postconf -e 'transport_maps = hash:/etc/postfix/transport';
postconf -e 'vacation_destination_recipient_limit = 1';


echo Spamassassin

#check if user spamd exists. Exit code 0 means it exists
if  ! id spamd 1>/dev/null 2>&1 ; then
	groupadd -g 5001 spamd
	useradd -u 5001 -g spamd -s /sbin/nologin -d /var/lib/spamassassin spamd
	mkdir /var/lib/spamassassin	
fi

chown spamd:spamd /var/lib/spamassassin


postconf -e virtual_transport=dovecot
postconf -e dovecot_destination_recipient_limit=1



cp /etc/default/spamassassin /etc/spamassassin/spamassassin.gobak.$2
cp /usr/share/groupoffice-mailserver/tpl/etc/default/spamassassin /etc/default/spamassassin

cp /etc/spamassassin/local.cf /etc/spamassassin/local.cf.gobak.$2
cp /usr/share/groupoffice-mailserver/tpl/etc/spamassassin/local.cf /etc/spamassassin

cp /etc/dovecot/dovecot.conf /etc/dovecot/dovecot.conf.gobak.$2
cp /usr/share/groupoffice-mailserver/tpl/etc/dovecot/dovecot.conf /etc/dovecot

cp /etc/postfix/master.cf /etc/postfix/master.cf.gobak.$2
cp /usr/share/groupoffice-mailserver/tpl/etc/postfix/master.cf /etc/postfix



php /usr/share/groupoffice-mailserver/configure.php
php /usr/share/groupoffice-mailserver/installpostfixadmin.php

invoke-rc.d spamassassin restart 3> /dev/null || true
invoke-rc.d dovecot restart 3> /dev/null || true
invoke-rc.d postfix restart 3> /dev/null || true

php /usr/share/groupoffice-mailserver/addadminaccount.php

#DEBHELPER#

exit 0
