<?php
require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Ha introducido un período de tiempo incorrecto';
$pm_add_hours_success = 'Los datos han sido guardados correctamente';

$pm_new_entry = 'Nueva entrada en';
$pm_fees = 'Costes';
$pm_new_fee = 'Nuevo coste';
$pm_users = 'Usuarios';
$pm_materials = 'Materiales';
$pm_new_material = 'Nuevo material';
$pm_project_data = 'Datos del proyecto desde';

$pm_value = 'Valor';
$pm_too_old = 'No puede introducir fechas más antiguas de una semana';

$pm_employee = 'Empleado';
$pm_project = 'Proyecto';
$pm_starttime = 'Fecha de inicio';
$pm_endtime = 'Fecha de finalización';
$pm_breaktime = 'Pausa';
$pm_this_week = 'introducido esta semana';
$pm_no_projects = 'No tiene ningún proyecto';
$pm_hours = 'Horas';
$pm_total_hours = 'Número total de horas';
$pm_client = 'Cliente';
$pm_created_at = 'Creado el';

$pm_show_all = 'Ver todo';
$pm_show_period = 'Ver desde';
$pm_to = 'a';
$pm_show_month = 'Ver el mes';

$pm_total_hours_days = 'Número total de horas/días';
$pm_projects_count = 'proyecto(s)';
$pm_show_data = 'Ver fecha';
$pm_new_project = 'Nuevo proyecto';
$pm_other_contacts = 'Otros contactos';
$pm_no_contacts = 'No tiene ningún contacto que pueda funcionar como cliente para este proyecto. Por favor, cree uno primero';

$pm_unit_value = 'Valor unitario';
$pm_units = 'Unidades';
$pm_mins = 'mins';
$pm_no_fees = 'No hay todavía ningún coste creado. Sólo un usuario con privilegios de administrador puede crear costes.';
$pm_fee = 'Coste';
$pm_no_contact = 'Ninguno';
$pm_load_period= 'Período';
$pm_load_type= 'Sólo carga datos desde';
$pm_total_fee = 'Coste total';
$pm_total_days = 'Total días';
$pm_total_units = 'Total unidades';
$pm_summary = 'Resumen';
$pm_this_entry = 'esta reserva';
$pm_entry = 'reserva';
//translation required
$pm_timer_started_at = 'Contador de tiempo iniciado a';
$pm_start_timer = 'Reloj en marcha';
$pm_stop_timer = 'Reloj parado';

$pm_start_date = 'Fecha de inicio';
$pm_end_date = 'Fecha de finalización';
$pm_responsible = 'Responsable';
$pm_status = 'Estado';

$pm_status_values[1] = 'Oferta';
$pm_status_values[2] = 'En curso';
$pm_status_values[3] = 'Esperando';
$pm_status_values[4] = 'Hecho';
$pm_status_values[5] = 'Facturado';

$pm_filter = 'Filtro';
$pm_project_exists = 'Ya existe un proyecto con este nombre';

$pm_clocked_in = 'Está marcando tiempo. Haga click aquí si desea parar el marcador';

$pm_alert = 'Este proyecto está a punto de caducar';
$pm_budget = 'Presupuesto';
$pm_probability = 'Probabilidad';
$pm_yours_only = 'Usted';
$pm_description = 'Descripción';

$pm_no_projects = 'No se ha encontrado ningún proyecto.';


//2.08
$pm_projects = 'Proyectos';
//2.12
$pm_select_project = 'Por favor, seleccione un proyecto';
$pm_already_booked = 'Ya tiene hecha una reserva en este período. Haga click %s para editar esta reserva'; //changed value. Search above
$pm_here = 'aquí';
$pm_load= 'Ver horas'; //chnaged. Search above

$pm_edit_data = 'Editar horas de trabajo';
$pm_enter_data = 'Introducir horas de trabajos';//changed, search above

//2.14
$pm_templates = 'Plantillas';
$pm_template = 'Plantilla';
$pm_new_template = 'Nueva plantilla';
$pm_no_templates = 'No se ha encontrado ninguna plantilla';

$pm_template_offset = 'Por-hacer comienza el';
$pm_template_after = 'después del proyecto nuevo empezar el';


$pm_new_template_event = 'Nuevo por-hacer';
$pm_duration = 'Duración';

$pm_no_template_events = 'No se ha encontrado ningún por-hacer';
$pm_no_template = 'No usar una plantilla';

$pm_put_events_in = 'poner por-hacer en';

//2.15
$pm_shift_events = 'Trasladar las notas y tareas asociadas cuando se cambie la fecha de inicio del proyecto';
?>
