<?php
require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Voc&ecirc; introduziu um per&iacute;odo de tempo inv&aacute;lido';
$pm_add_hours_success = 'Os dados como entrados abaixo foram conservados com sucesso';
$pm_already_booked = 'Voc&ecirc; j&aacute; reservou este per&iacute;odo';
$pm_new_entry = 'Nova entrada em';
$pm_fees = 'taxas';
$pm_new_fee = 'taxa nova';
$pm_users = 'utilizadores';
$pm_materials = 'materiais';
$pm_new_material = 'material novo';
$pm_project_data = 'Data do projeto de';
$pm_load= 'carga';
$pm_enter_data = 'introduzir dados';
$pm_value = 'Valor';
$pm_too_old = 'Voc&ecirc; n&atilde;o pode introduzir dados mais velhos que uma semana';

$pm_employee = 'Empregado';
$pm_project = 'Projeto';
$pm_starttime = 'Tempo de come&ccedil;o';
$pm_endtime = 'Tempo de conclusão';
$pm_breaktime = 'Tempo de suspens&atilde;o';
$pm_this_week = 'Introduzido nesta semana';
$pm_no_projects = 'Voc&ecirc; n&atilde;o tem projetos nenhuns';
$pm_hours = 'Horas';
$pm_total_hours = 'N&uacute;mero total das horas';
$pm_client = 'Cliente';
$pm_created_at = 'Criado em';

$pm_show_all = 'Mostrar tudo';
$pm_show_period = 'Mostrar de';
$pm_to = 'a';
$pm_show_month = 'Mostrar m&ecirc;s';

$pm_total_hours_days = 'Número total das horas/dias';
$pm_projects_count = 'projeto(s)';
$pm_show_data = 'mostrar dados';
$pm_new_project = 'projeto novo';
$pm_other_contacts = 'Outros contatos';
$pm_no_contacts = 'Voc&ecirc; n&atilde;o tem um contato que pode fun&ccedil;ionar como cliente para este projeto. Por favor cr&iacute;e um contato e primeiro e tente outra vez.';

$pm_unit_value = 'Valor de unidade';
$pm_units = 'Unidades';
$pm_mins = 'minutos';
$pm_no_fees = 'Taxas ainda n&atilde;o existem ou n&atilde;o foram criadas. Somente um utilizador com privil&eacute;gios administrativos pode criar taxas.';
$pm_fee = 'Taxa';
$pm_no_contact = 'Nenhum';
$pm_load_period= 'Per&iacute;odo';
$pm_load_type= 'Cargar dados por';
$pm_total_fee = 'Taxa total';
$pm_total_days = 'Dias totais';
$pm_total_units = 'Unidades totais';
$pm_summary = 'Sum&aacute;rio';

?>