<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Wählen Sie Benutzer und Gruppen aus, für welche Sie sichtbar sein möchten.";

//security
$security_text = "Geben Sie Ihr Passwort ein. Füllen Sie die Felder aus, die geändert werden sollen und klicken Sie auf 'Ok'.";
$security_current_password = "Aktuelles Passwort";
$security_new_password = "Neues Passwort";
$security_confirm_password = "Passwort wiederholen";
$security_new_authcode = "Neuer Authorisierungscode";
$security_confirm_authcode = "Authorisierungscode wiederholen";
$security_question = "Geheime Frage";
$security_answer = "Antwort";
$security_wrong_password = "Falsches Passwort.";
$security_tasks = "Aufgaben beendet";
$security_password_update = "Passwort geaendert.";
$security_authcode_update = "Authorisierungscodes geaendert.";
$security_question_update = "Frage und Antwort geaendert.";
$security_question_fail = "Die Frage oder die Antwort haben Sie nicht eingegeben.";

$acProfile = "Profil";
$acSecurity = "Passwort";
$acPrivacy = "Privatsphäre";
$acManager = "Ihr Account";
$acStatistics = "Statistik";
$acProfileText = "Klicken Sie auf 'Ok', um Ihr Profil zu ändern. Die mit * gekennzeichneten Felder müssen ausgefüllt werden.";
$acTitle = "Ihr Account";
$ac_login_info = "Anmeldeinformation";
$ac_registration_time = "Registrierungszeit";
$ac_lastlogin = "Letzte Anmeldung";
$ac_logins = "Anmeldungen gesamt";
$ac_disk_usage = "Plattenverbrauch";
$ac_max_diskspace = "Max Plattenkapazität";
$ac_available_diskspace = "Verfügbare Plattenkapazität";
$ac_used_diskspace = "Verbrauchte Plattenkapazität";
$ac_used = "In Gebrauch";

$ac_add_user = 'Zugriffsanforderung';
$ac_auth_error = 'Waehrend der Berechtigungsanforderung ist ein Fehler aufgetreten. Bitte erneut versuchen.';
$ac_auth_success = 'Dieser Benutzer hat ab sofort die Berechtigung auf Ihre Daten zuzugreifen. Eine Bestaetigungsnachricht wurde an den Benutzer versandt.';
$ac_auth_decline = 'Eine Nachricht ueber eine Ablehnung der Anforderung wurde an den Benutzer versandt.';
$ac_auth_accept_mail_title = 'Group-Office Zugriffsberechtigung erteilt';
$ac_auth_decline_mail_title = 'Group-Office Anforderung auf Zugriffsberechtigung abgelehnt';
$ac_salutation = 'Sehr geehrte(r) Frau/Herr';
$ac_auth_accept_mail_body = 'hat Ihre Anforderung auf Zugriffsberechtigung befuerwortet.';
$ac_auth_decline_mail_body = 'hat Ihre Anforderung auf Zugriffsberechtigung abgelehnt.';
$ac_request_auth = 'hat eine Zugriffsberechtigung auf Ihre Daten angefordert. Moechten Sie diesem Benutzer eine Zugriffsberechtigung auf Ihre Daten erteilen?';
$ac_request_auth_mail_title ='Group-Office Anforderung auf Zugriffsberechtigung';
$ac_invalid_email = 'Die eingegebene E-Mail Adresse ist innerhalb des Systems nicht bekannt. Bitte erneut versuchen.';
$ac_request_mail_body_prefix = 'Eine Nachricht mit der Anforderung auf Datenzugriff wurde an ';
$ac_request_mail_body_suffix = 'versandt.';
$ac_auth_text = 'Bitte die E-Mail Adresse des Benutzers eingeben, auf dessen Daten Sie eine Zugriffsberechtigung erteilt haben möchten.';

$ac_accept = 'Akzeptieren';
$ac_decline = 'Ablehnen';
$ac_salutation = 'Sehr geehrte(r)';
