<?php
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = 'propriedades';
$admin_modules = 'm&oacute;dulos';
$strPath = 'Trajeto';
$admin_invalid_path = 'Voc&ecirc; entrou em um trajeto inv&aacute;lido';
$admin_overview = 'vista geral';
$admin_module = 'M&oacute;dulo';
$admin_modules_text = 'Selecione os m&oacute;dulos que voc&ecirc; deseja usar e clique sobre \''.$cmdSave.'\'.<br />Clique sobre os m&oacute;dulos ativos para mudar suas permiss&otilde;es.';
$admin_bookmarks_text = 'Adicione os bookmarks aqui que ser&atilde;o criados automaticamente quando voc&ecirc; regista um utilizador novo.';
$admin_bookmark_new_window = 'Abrir o bookmark dentro de uma janela nova';
$admin_menus_text = "Selecione os menus que voc&ecirc; deseja usar e clique 'guardar'";
$admin_start_module = 'Come&ccedil;ar Group-Office em';
$admin_menus = "menus";
$admin_formats = "formato de datas";
$admin_date_formats_text = 'Adicione os formatos de data no <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">formato de PHP</a> com a descri&ccedil;&atilde;o e clique sobre OK.';
?>
