<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('filesystem'));

$strLookIn = 'Podívat se na';
$strType = "Typ";
$strModified = "Měněno";
$strCreated = "Vytvořeno";
$strAccessed = "Použito";
$strSize = "Velikost";
$fbRefresh = "Obnovit";
$fbProperties = "Vlastnosti";
$fbNewFolder = "Nová složka";
$fbDelete = "Smazat";
$fbCut = "Vyjmout";
$fbPaste = "Vložit";
$fbCopy = "Kopírovat";
$fbFiletypes = "Typy souborů";
$fbSharing = "Sdíleni";
$fbShares = "Sdílené složky";
$fbShare = "Sdílená složka";
$fbPath = "Cesta";
$fbFolders = "Složky";
$fbNoSelect = "Nezvolil jste žádnou položku. Pro výběr klikněte na obrázek vedle jména.";
$fbConfirmDelete = "Potvrďte smazání";
$fbWritePermissions = "Práva k zápisu";
$fbReadPermissions = "Práva ke čtení";
$fbGeneral = "Obecné";
$fbConfirmOverwrite = "Potvrďte přepsání";
$strOverwritePrefix = "Jste si jistí že chcete přepsat ";
$strOverwriteSuffix = "?";
$fbDescription = "Popis";
$fbLocation = "Umístění";
$fbUpload = "Nahrát";
$fbUpload_text = "Zvolte soubor pro nahrání";
$fbUpload_nofile = "Nebyl nahrán žádný soubor.";
$fbVersions = "Verze";
$fbDelete_version = "Určitě chcete smazat tuto verzi?";
$fbFolderExists = "Složka už existuje.";
$fbEmailFile = "Soubor s E-mailem";
$fbFolder = "Složka";

$fbNoFile = "Pokoušíte se nahrát příliš velký soubor.<br />Maximální velikost pro nahrávané soubory je: ";
$fbPleaseWait = "Prosím vyčkejte. Posílám data...";
$fbFilename = "Název souboru";
$fbUpLevel = "O úroveň výš";
$fbItems = "položka(y)";
$fbFolderSize = "Velikost složky";
$fbMaxUploadSize = "Maximální velikost";
$ml_file_too_big = "Pokoušíte se připojit příliš velký soubor. Maximální velikost pro nahrávané soubory je: ";
$cmdSearch = "Hledej";
$fbNoRightToOverwrite = "Soubor už existuje a nemáte oprávnění ho přepsat.";
$fbSaveFile = "Uložit soubor jako...";
$fbNameExists = "Takové jméno už ve složce existuje.";
$fbThis = 'tento';
$fbFiles = 'Soubory';
$fs_activate_sharing = 'Nastavit sdílení';
$fs_calculate_folder_size = 'Spočítat velikost složky';
$fs_no_multi_select = 'Pro tuto akci můžete zvolit jen jeden soubor';
$fs_search = 'Hledat';
$search_title = "Hledat soubory a složky";
$fs_keyword = 'Klíčové slovo';
$fs_enter_keyword = 'Prosím zadejte klíčové slovo';
$fs_modified_before = 'Změněno před';
$fs_modified_after = 'Změněno po';

//translation required
$fb_compress='Sbalit';
$fb_decompress='Rozbalit';
$fb_failed_to_create = 'Nelze vytvořit archív.';
$fb_failed_to_extract = 'Chyba při rozbalování';
$fb_compression_type = 'Typ archivu';
$fbFreeQuotaSpace = 'Volné místo ve vaší složce';

//2.11
$fb_unkown_compression = 'Neznámý typ archívu';
$fs_new_doc = 'Nový dokument';
$fs_cleanup = 'Vyčistit HTML';
$fbMultipleFiles = 'Více souborů';
$fbSelect = "Zvolte soubor"; //changed
?>
