<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));
$sum_welcome_to='Pozdravljeni v';
$sum_you_have='Imate';
$sum_new_messages='<b>neprebranih</b> e-mail sporočil';
$sum_new_message='<b>neprebrano</b> e-mail sporočilo';
$sum_no_new_mail='Ni neprebrane pošte';
$sum_manage_announcements='Organiziraj oznanila';
$sum_announcements_count='oznanila';
$sum_announcements_count_single='oznanilo';
$sum_no_announcements='Ni najdenih oznanil';
$sum_due_time='Prikaži dokler';
$sum_new_announcement='Novo oznanilo';
$sum_private='Zasebno';
$sum_today='Danes';
$sum_tommorow='Jutri';
$sum_unfinished='Nedokončano';
?>