<?php
$images['email']='22x22/email.png';

$images['message']='16x16/message.png';
$images['message_answered']='16x16/message_answered.png';
$images['compose']='16x16/mail_new.png';
$images['reply']='16x16/mail_reply.png';
$images['reply_all']='16x16/mail_replyall.png';
$images['forward']='16x16/mail_forward.png';

$images['flag']='16x16/flag.png';
$images['attach']='16x16/attach.png';

$images['accounts']='16x16/accounts.png';
