<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Willkommen in ";
$strUseMenu = "Bitte das Menü oder die unteren Links verwenden für die Arbeit mit ";
$click_to_login = "Zum Anmelden hier klicken.";
$login_text = "Zum Anmelden Benutzername und Passwort eingeben";
$login_username = "Benutzername";
$login_password = "Passwort";
$login_missing_field = "Benutzername oder Passwort wurde nicht eingegeben.";
$login_bad_login = "Benutzername oder Passwort falsch";
$login_remind = "Ich möchte angemeldet bleiben bis ich mich mit logout abmelde.";
$login_language = 'Sprache';

//2.12
$login_register = 'oder %s klicken, um sich registrieren zu lassen';
$login_here = "hier";
$login_lost_password = 'Passwort vergessen?';
$login_lost_password_title = 'Passwort anfordern';
$login_lost_password_text= 'Bitte Ihre Email-Adresse unten eingeben. Ihr Passwort wird Ihnen per Email zugesandt.';
$login_lost_password_mail_body = "Sie haben für %s ein neues Passwort angefordert. Die neuen Anmeldedaten für %s lauten:\n\nBenutzername: %s\nPasswort: %s\n\nViel Glück!";
$login_new_password = 'Neues Passwort';
$login_lost_password_success = 'Ein neues Passwort ist an %s versandt worden';
$login_lost_password_failed = 'Leider ist diese Email-Adresse \'%s\' hier nicht registriert.';

//2.14
$login_fullscreen = $GO_CONFIG->title.' wurde automatisch im neuen Fenster im Vollbildmodus geöffnet. Sie können dieses Fenster schließen oder Group-Office neu starten.';
$login_start = 'Neu starten';
?>
