<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Selecione os utlizadores e os grupos a que voc&ecirc; quer ser vis&iacute;vel.";

//security
$security_text = "Indroduza a sua senha e os campos que voc&ecirc; quer mudar e clique 'Guardar'";
$security_current_password = "Senha atual";
$security_new_password = "Senha nova";
$security_confirm_password = "Confirme a senha";
$security_new_authcode = "C&oacute;digo novo de autoriza&ccedil;&atilde;o";
$security_confirm_authcode = "Confirme o c&oacute;digos de autoriza&ccedil;&atilde;o";
$security_question = "Pergunta secreta";
$security_answer = "Resposta";
$security_wrong_password = "Senha errada.";
$security_tasks = "Tarefas terminadas.";
$security_password_update = "A senha atualizou.";
$security_authcode_update = "Os c&oacute;digos de autoriza&ccedil;&atilde;o atualizaram.";
$security_question_update = "Pergunta e resposta atualizada.";
$security_question_fail = "Voc&ecirc; n&atilde;o preencheu a pergunta e a resposta ..";

$acProfile = "Perfil";
$acSecurity = "Seguran&ccedil;a";
$acPrivacy = "Privacidade";
$acManager = "Sua conta";
$acStatistics = "Estatisticas";
$acProfileText = "Clique sobre 'Guardar' para mudar seu perfil. Os campos marcados com a * s&atilde;o requeridos.";
$acTitle = "Sua conta";
$ac_login_info = "Informa&ccedil;&atilde;o sobre o inicio da sess&atilde;o";
$ac_registration_time = "Tempo do registo";
$ac_lastlogin = "Uacute;ltimo inicio de uma sess&atilde;o";
$ac_logins = "Inicios totais";
$ac_disk_usage = "Uso do disco";
$ac_max_diskspace = "Espa&ccedil;o de disco m&aacute;ximo ";
$ac_available_diskspace = "Espa&ccedil;o de disco dispon&iacute;vel ";
$ac_used_diskspace = "Espa&ccedil;o de disco usado";
$ac_used = "usado";
?>