<?php

// LANG: "fr", ENCODING: UTF-8
// Author: A. Kermorvant : armek@akserver.dyndns.org
// 24 Oct 2004

// FOR TRANSLATORS:
//
//   1. PLEASE PUT YOUR CONTACT INFO IN THE ABOVE LINE
//      (at least a valid email address)
//
//   2. PLEASE TRY TO USE UTF-8 FOR ENCODING;
//      (if this is not possible, please include a comment
//       that states what encoding is necessary.)

require_once($GO_LANGUAGE->get_fallback_language_file('groups'));

$groups_title = "groupes utilisateurs";
$groups_tab = "groupes";
$groups_saved = "Préférences enregistrées.";
$groups_text = "Cliquez sur un groupe pour voir ses propriétés.";
$groups_users_in = "Utilisateurs dans le groupe ";
$groups_no_contacts = "Vous n'avez aucun membre de contact à choisir. Utilisez le carnet d'adresses pour ajouter des membres à vos contacts.";

$add_group_text = "Entrez un nom et cliquez sur 'Ok' pour ajouter un nouveau groupe.";
$add_group_fail = "Impossible d'ajouter le groupe. Merci de réessayer.";
$add_group_success = "Le groupe a été ajouté avec succès.";
$add_group_exists = "Le nom existe déjà. Merci d'en choisir un autre.";
$add_group_no_name = "Vous n'avez pas spécifié de nom.";
$groups_everyone = "Ce groupe est spécial et contient tous les utilisateurs. Vous ne pouvez pas modifier ce groupe.";
$groups_users_in1 = "utilisateur(s) dans le groupe";
$groups_no_users = "Il n'y a pas d'utilisateurs dans ce groupe.";
$groups_users_in_select = "Choisissez les utilisateurs que vous souhaitez ajouter à ce groupe :";

$groups_new_group = 'Nouveau groupe';
$groups_members = 'Membres';
?>
