<?php
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));

$groups_title = "grupos de utilizadores";
$groups_tab = "grupos";
$groups_saved = "Os ajustes conservaram.";
$groups_text = "Clique num grupo para examinar as suas propriedades.";
$groups_users_in = "Utilizadores no grupo ";
$groups_no_contacts = "Voc&ecirc; n&atilde;o tem nenhuns contatos a seleccionar.<br /> Use o Livro de Endere&ccedil;os para adicionar membros &agrave; lista de contatos.";

$add_group_text = "Encorpore um nome e clique sobre 'OK' para adicionar um grupo novo.";
$add_group_fail = "A adi&ccedil;&atilde;o do grupo falhou. Por favor tente outra vez.";
$add_group_success = "O grupo foi adicionado com sucesso.";
$add_group_exists = "Esse nome j&aacute; existe. Por favor escolha outro nome.";
$add_group_no_name = "Voc&ecirc; n&atilde;o especificou um nome.";
$groups_everyone = "Este grupo &eacute; um grupo especial e contem todos os utilizadores. Voc&ecirc; n&atilde;o pode modificar este grupo.";
$groups_users_in1 = "utilizador(es) no grupo";
$groups_no_users = "N&atilde;o existem utilizadores neste grupo.";
$groups_users_in_select = "Selecione os utilizadores que quer adicionar a este grupo:";
?>
