<?php
/**
 * Copyright Intermesh
 *
 * This file is part of Group-Office. You should have received a copy of the
 * Group-Office license along with Group-Office. See the file /LICENSE.TXT
 *
 * If you have questions write an e-mail to info@intermesh.nl
 *
 * @version $Id$
 * @copyright Copyright Intermesh
 * @author Merijn Schering <mschering@intermesh.nl>
 *
 * @package Tools
 * @subpackage Database backup
 */

require_once("../../Group-Office.php");
$GO_SECURITY->authenticate();
$GO_MODULES->authenticate('tools');
require_once($GO_LANGUAGE->get_language_file('tools'));


$browser = detect_browser();

$filename = 'groupoffice-dbbackup-'.date('YmdGi').'.sql';

//header('Content-Transfer-Encoding: binary');
header('Content-Type: application/download');
header('Content-Disposition: attachment; filename="'.$filename.'"');
header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
header('Pragma: no-cache,public');


echo "#Group-Office version ".$GO_CONFIG->version."\n";
echo "#Generated by Group-Office DB backup tool\n";
echo "#Written by Merijn Schering <mschering@intermesh.nl>\n\n\n";



$db = new db();

$db->query('SHOW TABLES;');
while($db->next_record(DB_BOTH))
{
	$tables[]=$db->f(0);
}

foreach($tables as $table)
{
	$db->query("SHOW CREATE TABLE `$table`");
	
	if($db->next_record(DB_BOTH))
	{
		echo "\n#Create table ".$table."\n\n";		
		
		
		echo $db->f(1);
		echo ";\n\n";
	}else {
		die('Failed to dump table "'.$table.'"');
	}
	
	echo "#Dumping data for ".$table."\n\n";
	
	$db->query("SELECT * FROM `$table`");
	
	while($db->next_record(DB_ASSOC))
	{
		if(count($db->record))
		{
			$fields=array();
			$values=array();
			foreach($db->record as $field=>$value)
			{
				$fields[]=$field;
				$values[]=$value;
			}
			
			echo "REPLACE INTO `$table` (`"; 
			
			echo implode('`,`', $fields)."`) VALUES ('";
			echo implode('\',\'',$values)."');\n";
		}
	}
}