#!/bin/sh


# Use debconf.
. /usr/share/debconf/confmodule

php /usr/share/groupoffice-servermanager/configure.php
php /usr/share/groupoffice-servermanager/installservermanager.php

a2enmod vhost_alias

chown -R www-data:www-data /var/www/groupoffice

/etc/init.d/apache2 restart 3> /dev/null || true

exit 0
