#!/bin/sh
set -e

# Use debconf.
. /usr/share/debconf/confmodule

php /usr/share/groupoffice-servermanager/configure.php
php /usr/share/groupoffice-servermanager/installservermanager.php

a2enmod vhost_alias

chown -R www-data:www-data /home/govhosts

invoke-rc.d apache2 restart 3> /dev/null || true

php /usr/share/groupoffice-servermanager/upgradeinstallation.php

exit 0
