<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Idioma";
$pref_theme = "Tema";
$pref_date_format = "Formato de fecha";
$pref_thousands_seperator = "Separador de millares";
$pref_decimal_seperator = "Separador decimal";
$pref_mail_client = "Usar el cliente de correo de Group-Office para enviar mensajes.";
$pref_look = "Aspecto";
$pref_notations = "Parámetros regionales";
$pref_currency = 'Moneda';
$pref_region_code = 'Región';
$pref_max_rows_list = 'Número máximo de filas en las listas';
$pref_unlimited = 'Ilimitado';
$pref_timezone = 'Zona horaria';
$pref_time_format = "Formato de hora";
$pref_startmodule = 'Empezar con el módulo';

//2.01
$pref_first_weekday = 'Primer día de la semana';

//2.05
$adjust_to_dst = 'Ajustar la hora de Verano/Invierno automáticamente';

//2.08
$pref_name_order = 'Ordenar nombres por';

//2.14
$pref_use_checkbox_select = 'Seleccionar múltiples filas sin usar la tecla CTRL';
