<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));

$sync_with = 'Sincronitza amb:';
$sync_calendar = 'Calendari';
$sync_addressbook = 'Llibreta d\'adreces';
$sync_server_is_master = 'Les dades de Group-Office són més importants que les dades del dispositiu convidat';
$sync_sync_private = 'Sincronitza les cites privades també';
$sync_devices = 'Dispositius';

$sync_last_calendar_sync = 'Darrera sincronització de calendari';
$sync_last_addressbook_sync = 'Darrera sincronització de llibreta d\'adreces';

$sync_never = 'Mai';
?>
