<?php

// LANG: "fr", ENCODING: UTF-8
// Author: A. Kermorvant : armek@akserver.dyndns.org
// 24 Oct 2004

// FOR TRANSLATORS:
//
//   1. PLEASE PUT YOUR CONTACT INFO IN THE ABOVE LINE
//      (at least a valid email address)
//
//   2. PLEASE TRY TO USE UTF-8 FOR ENCODING;
//      (if this is not possible, please include a comment
//       that states what encoding is necessary.)

require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Langue";
$pref_theme = "Thème";
$pref_date_format = "Format de la date";
$pref_thousands_seperator = "Séparateur des milliers";
$pref_decimal_seperator = "Séparateur décimal";
$pref_mail_client = "Utiliser le client mail de Group-Office pour envoyer le courrier.";
$pref_look = "Apparence";
$pref_notations = "Notations";
$pref_currency = 'Monétaire';
$pref_region_code = 'Région';
$pref_max_rows_list = 'Nombre maximum de lignes dans les listes';
$pref_unlimited = 'Illimité';
$pref_timezone = 'Fuseau horaire';
$pref_time_format = "Format horaire";
$pref_startmodule = 'Commencer avec le module'; //Start in module
$pref_first_weekday = 'Premier jour de la semaine';
$adjust_to_dst = 'Ajuster automatiquement l\'économie d\'énergie'; //Daylight Savings Time';

$pref_name_order = 'Trier les noms par';

//2.01
$pref_first_weekday = 'Premier jour de la semaine';

//2.05
$adjust_to_dst = 'Ajuster automatiquement le temps sur l\'heure d\'hiver ou d\'été';

//2.08
$pref_name_order = 'Trié les noms par';

//2.14
$pref_use_checkbox_select = 'Sélectionne plusieurs lignes sans utiliser la touche CTRL';

//2.15
$pref_date_seperator = 'Séparateur de date';
