<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Idioma";
$pref_theme = "Tema";
$pref_date_format = "Formato da data";
$pref_thousands_seperator = "Separador dos milhares";
$pref_decimal_seperator = "Separador dos decimais";
$pref_mail_client = "Usar o Group-Office m&oacute;dulo de correio eletr&ocirc;nico para enviar E-mail.";
$pref_look = "Estilo";
$pref_notations = "Nota&ccedil;&otilde;es";
$pref_currency = 'Moeda';
$pref_region_code = 'Regi&atilde;o';
?>
