#!/bin/sh
set -e

chown -R www-data:www-data /home/groupoffice
chmod 666 /etc/groupoffice/config.php

. /usr/share/debconf/confmodule

. /usr/share/dbconfig-common/dpkg/postinst.mysql
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_generate_include=php:/etc/groupoffice/config-db.php
dbc_go groupoffice $@

#for testing
ln -s /var/www/trunk/www /usr/share/groupoffice

/etc/init.d/apache2 reload > /dev/null || true

exit 0

