#!/bin/sh
set -e

. /usr/share/debconf/confmodule

. /usr/share/dbconfig-common/dpkg/postinst.mysql
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_generate_include=php:/etc/groupoffice/config-db.php
dbc_go groupoffice-com $@

#for testing
if [ ! -e /usr/share/groupoffice ]; then
	ln -s /var/www/community/trunk/www /usr/share/groupoffice
fi

invoke-rc.d apache2 reload > /dev/null || true


php /usr/share/groupoffice-install-scripts/configure.php

cd /usr/share/groupoffice/install
php ./autoinstall.php /etc/groupoffice/config.php
php ./upgrade.php /etc/groupoffice/config.php

chown -R www-data:www-data /home/groupoffice

db_input high groupoffice/completed || true
db_go

exit 0

