<?php
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));

$groups_title = "Benutzergruppen";
$groups_tab = "Gruppen";
$groups_saved = "Einstellungen gespeichert.";
$groups_text = "Bitte auf eine Gruppe klicken, um deren Eigenschaften einzusehen.";
$groups_users_in = "Benutzer in der Gruppe ";
$groups_no_contacts = "Ihnen stehen keine Kontakte zur Auswahl.<br /> Bitte benutzen Sie das Adressbuch, um Mitglieder in Ihre Kontaktliste aufzunehmen.";

$add_group_text = "Bitte einen Namen eingeben und auf 'speichern' klicken, um eine neue Gruppe anzulegen.";
$add_group_fail = "Fehler beim Anlegen der Gruppe aufgetreten. Bitte erneut versuchen.";
$add_group_success = "Gruppe erfolgreich angelegt.";
$add_group_exists = "Der Name existiert bereits. Bitte einen anderen Namen waehlen.";
$add_group_no_name = "Sie haben keinen Namen angegeben.";
$groups_everyone = "Das ist eine spezielle Gruppe. Diese Gruppe beherbergt alle Benutzer und kann daher nicht modifiziert werden.";
$groups_users_in1 = "Benutzer in der Gruppe";
$groups_no_users = "Dieser Gruppe sind keine Benutzer zugeordnet.";
$groups_users_in_select = "Bitte die Benutzer waehlen, die dieser Gruppe zugeordnet werden sollen:";
$groups_new_group = 'Neue Gruppe';
$groups_members = 'Mitglieder';

//2.13
$lang_modules['groups'] = 'Gruppen';
?>
