<?php

// LANG: "fr", ENCODING: UTF-8
// Author: A. Kermorvant : armek@akserver.dyndns.org
// 24 Oct 2004

// FOR TRANSLATORS:
//
//   1. PLEASE PUT YOUR CONTACT INFO IN THE ABOVE LINE
//      (at least a valid email address)
//
//   2. PLEASE TRY TO USE UTF-8 FOR ENCODING;
//      (if this is not possible, please include a comment
//       that states what encoding is necessary.)

require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = 'Propriétés';
$admin_modules = 'Modules';
$strPath = 'Chemin';
$admin_invalid_path = 'Vous avez entré un chemin invalide';
$admin_overview = 'Aperçu';
$admin_module = 'Module';
$admin_modules_text = 'Cliquez sur Installer ou Désintaller. Attention, déinstaller un module supprime vos données.';
$admin_bookmarks_text = 'Ajouter un signet içi qui sera automatiquement créé lorsque vous enregistrerez un nouvel utilisateur.';
$admin_bookmark_new_window = 'Ouvrir le signet dans une nouvelle fenêtre';
$admin_menus_text = "Vérifiez le menu que vous souhaitez utiliser et cliquez sur 'enregistrer'";
$admin_start_module = 'Démarrer Group-Office dans';
$admin_menus = "Menus";
$admin_formats = "formats des dates";
$admin_date_formats_text = 'Ajouter les formats des dates dans <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">les formats PHP</a> avec une description et cliquez sur Ok.';

$strAuthors = 'Autheur(s)';
$strVersion = 'Version';
$strReleaseDate = 'Date de validation';
$strDescription = 'Description';
$strStatus = 'Status';
$strNoModuleInfo = 'Pas de module d\'information disponible.';

$cmdInstall = 'Installer';
$cmdUninstall = 'Désinstaller';
$strConfirmUninstallPrefix = 'Etes-vous sure de vouloir désinstaller ';
$strConfirmUninstallSuffix = '?';
?>
