<?php
require('../../www/Group-Office.php');

require_once ($GO_MODULES->modules['addressbook']['class_path']."vcard.class.inc.php");
require_once ($GO_CONFIG->class_path."ical2array.class.inc");


$vcard_text='BEGIN:VCARD
VERSION:2.1
N:achternaam;voornaam;Tussen;Title;
BDAY:19800911
NOTE;ENCODING=QUOTED-PRINTABLE;CHARSET=UTF-8:=0D=0A
TEL;WORK;FAX:fax werk
TEL;VOICE;WORK:tel werk
TEL;VOICE;WORK:
TEL;CAR;VOICE:
CATEGORIES:
TEL;WORK;PREF:
FN:voornaam achter
EMAIL;INTERNET:email1@test.nl
EMAIL;INTERNET;HOME:email3@test.nl
EMAIL;INTERNET;WORK:email2@test.nl
TITLE:Functi
TEL;VOICE;HOME:tel
TEL;VOICE;HOME:
TEL;HOME;FAX:fax
URL;HOME:
PRIORITY:1
TEL;CELL:mob
NICKNAME:
TEL;FAX:
TEL;VOICE:
TEL;PAGER:
TEL;PREF;VOICE:
ROLE:
CLASS:PUBLIC
URL:
ORG:;afdeling;
ADR;HOME:;;adres huisn;woonpl;prov;postcode;NL
ADR:;;;;;;
ADR;WORK:;;;;;;
PHOTO:
X-ANNIVERSARY:
X-FUNAMBOL-BILLINGINFO:
TEL;X-FUNAMBOL-CALLBACK:
X-FUNAMBOL-CHILDREN:
X-FUNAMBOL-COMPANIES:
X-FUNAMBOL-FOLDER:DEFAULT_FOLDER
X-FUNAMBOL-GENDER:0
X-FUNAMBOL-HOBBIES:
EMAIL;INTERNET;HOME;X-FUNAMBOL-INSTANTMESSENGER:
X-FUNAMBOL-INITIALS:v.T.a.
X-FUNAMBOL-LANGUAGES:
X-MANAGER:
X-FUNAMBOL-MILEAGE:
X-FUNAMBOL-ORGANIZATIONALID:
END:VCARD';

$vcard = new vcard();
$record = $vcard->vcf_to_go($vcard_text);

var_dump($record);

