<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Bienvenido a ";
$strUseMenu = "Use el menú o haga click en los accesos directos para iniciar cualquier aplicación de ";
$click_to_login = "Haga click aquí para entrar.";
$login_text = "Introduzca su nombre de usuario y contraseña para iniciar la sesión";
$login_username = "Nombre de usuario";
$login_password = "Contraseña";
$login_missing_field = "No ha introducido el nombre de usuario o la contraseña.";
$login_bad_login = "Nombre de usuario o contraseña incorrectos.";
$login_remind = "Conservar la sesión hasta que pulse el botón de salir.";
$login_language = 'Idioma';

//2.12
$login_register = 'o haga click en %s para firmar';
$login_here = "aquí";
$login_lost_password = '¿Contraseña perdida?';
$login_lost_password_title = 'Recuperar contraseña';
$login_lost_password_text= 'Por favor, introduzca su correo electrónico y se le enviará una nueva contraseña a su dirección.';
$login_lost_password_mail_body = "ha pedido una nueva contraseña para %s. Sus datos para entrar como %s son:\n\nNombre de usuario: %s\nContraseña: %s\n\n¡Buena suerte!";
$login_new_password = 'Nueva contraseña';
$login_lost_password_success = 'Ha sido enviada una nueva contraseña a %s';
$login_lost_password_failed = 'Lo siento, la dirección de correo electrónico \'%s\' no está registrada en este sistema.';

//2.14
$login_fullscreen = $GO_CONFIG->title.' ha sido abierta en pantalla completa automáticamente. Puede cerrar esta ventana o iniciar Group-Office de nuevo.';
$login_start = 'Iniciar de nuevo';
?>
